SUBROUTINE ccsdtq_e(d_f1,d_i0,d_t1,d_t2,d_v2,f1_offset,i0_offset,t1_offset,t2_offset,v2_offset)
!$Id$
!This is a Fortran90 program generated by Tensor Contraction Engine v.1.0
!
!
!i0 ( )_tf + = 1 * Sum ( p5 h6 ) * t ( p5 h6 )_t * i1 ( h6 p5 )_f
!    i1 ( h6 p5 )_f + = 1 * f ( h6 p5 )_f
!    i1 ( h6 p5 )_vt + = 1/2 * Sum ( h4 p3 ) * t ( p3 h4 )_t * v ( h4 h6 p3 p5 )_v
!i0 ( )_vt + = 1/4 * Sum ( h3 h4 p1 p2 ) * t ( p1 p2 h3 h4 )_t * v ( h3 h4 p1 p2 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_i0
INTEGER :: d_t1
INTEGER :: d_i1
INTEGER :: d_t2
INTEGER :: d_v2
INTEGER :: d_f1
INTEGER :: length
INTEGER :: i0_offset(*)
INTEGER :: t1_offset(*)
INTEGER :: t2_offset(*)
INTEGER :: v2_offset(*)
INTEGER :: f1_offset(*)
INTEGER, ALLOCATABLE :: i1_offset(:)
REAL*8 :: size_i1
CHARACTER(LEN=255) :: filename
CALL OFFSET_ccsdtq_e_1_1_a(length)
ALLOCATE(i1_offset(length*2+1))
CALL OFFSET_ccsdtq_e_1_1_b(i1_offset,size_i1,length)
CALL UT_TCE_FILENAME('ccsdtq_e_1_1_i1',filename)
CALL CREATEFILE(filename,d_i1,size_i1)
CALL ccsdtq_e_1_1(d_f1,f1_offset,d_i1,i1_offset)
CALL ccsdtq_e_1_2(d_t1,t1_offset,d_v2,v2_offset,d_i1,i1_offset)
CALL RECONCILEFILE(d_i1,size_i1)
CALL ccsdtq_e_1(d_t1,t1_offset,d_i1,i1_offset,d_i0,i0_offset)
CALL DELETEFILE(d_i1)
DEALLOCATE(i1_offset)
CALL ccsdtq_e_2(d_t2,t2_offset,d_v2,v2_offset,d_i0,i0_offset)
RETURN
END
SUBROUTINE ccsdtq_e_1(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( )_tf + = 1 * Sum ( p5 h6 ) * t ( p5 h6 )_t * i1 ( h6 p5 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: dimc
INTEGER :: p5b
INTEGER :: h6b
INTEGER :: p5b_1
INTEGER :: h6b_1
INTEGER :: h6b_2
INTEGER :: p5b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
IF (next == count) THEN
IF (0 == ieor(irrep_t,irrep_f)) THEN
dimc = 1
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p5b = noab+1,noab+nvab
DO h6b = 1,noab
IF (spin(p5b) == spin(h6b)) THEN
IF (ieor(sym(p5b),sym(h6b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p5b,h6b,p5b_1,h6b_1)
CALL TCE_RESTRICTED_2(h6b,p5b,h6b_2,p5b_2)
dim_common = range(p5b) * range(h6b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = 1
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (p5b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p5b),range(h6b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - noab - 1 + nvab * (h6b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(h6b),range(p5b),1,2,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_0(c_sort,c,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,0)
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdtq_e_1_1(d_a,a_offset,d_c,c_offset)
!i1 ( h6 p5 )_f + = 1 * f ( h6 p5 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h6b
INTEGER :: p5b
INTEGER :: dimc
INTEGER :: h6b_1
INTEGER :: p5b_1
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: a_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h6b = 1,noab
DO p5b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h6b)+spin(p5b) /= 4)) THEN
IF (spin(h6b) == spin(p5b)) THEN
IF (ieor(sym(h6b),sym(p5b)) == irrep_f) THEN
dimc = range(h6b) * range(p5b)
CALL TCE_RESTRICTED_2(h6b,p5b,h6b_1,p5b_1)
dim_common = 1
dima_sort = range(h6b) * range(p5b)
dima = dim_common * dima_sort
IF (dima > 0) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(p5b_1 - 1 + (noab+nvab) * (h6b_1 - 1)))
CALL TCE_SORT_2(a,a_sort,range(h6b),range(p5b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(c(dimc))
CALL TCE_SORT_2(a_sort,c,range(p5b),range(h6b),2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p5b - noab - 1 + nvab * (h6b - 1)))
DEALLOCATE(c)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE OFFSET_ccsdtq_e_1_1_b(a_offset,size,length)
!i1 ( h6 p5 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: addr
INTEGER :: h6b
INTEGER :: p5b
INTEGER :: a_offset(*)
REAL*8 :: size
a_offset(1) = length
addr = 0
size = 0.0d0
DO h6b = 1,noab
DO p5b = noab+1,noab+nvab
IF (spin(h6b) == spin(p5b)) THEN
IF (ieor(sym(h6b),sym(p5b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(h6b)+spin(p5b) /= 4)) THEN
addr = addr + 1
a_offset(addr+1) = p5b - noab - 1 + nvab * (h6b - 1)
a_offset(length+addr+1) = size
size = size + dfloat(range(h6b)) * dfloat(range(p5b))
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE OFFSET_ccsdtq_e_1_1_a(length)
!i1 ( h6 p5 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: h6b
INTEGER :: p5b
length = 0
DO h6b = 1,noab
DO p5b = noab+1,noab+nvab
IF (spin(h6b) == spin(p5b)) THEN
IF (ieor(sym(h6b),sym(p5b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(h6b)+spin(p5b) /= 4)) THEN
length = length + 1
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE ccsdtq_e_1_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i1 ( h6 p5 )_vt + = 1/2 * Sum ( h4 p3 ) * t ( p3 h4 )_t * v ( h4 h6 p3 p5 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h6b
INTEGER :: p5b
INTEGER :: dimc
INTEGER :: p3b
INTEGER :: h4b
INTEGER :: p3b_1
INTEGER :: h4b_1
INTEGER :: h6b_2
INTEGER :: h4b_2
INTEGER :: p5b_2
INTEGER :: p3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h6b = 1,noab
DO p5b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h6b)+spin(p5b) /= 4)) THEN
IF (spin(h6b) == spin(p5b)) THEN
IF (ieor(sym(h6b),sym(p5b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(h6b) * range(p5b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p3b = noab+1,noab+nvab
DO h4b = 1,noab
IF (spin(p3b) == spin(h4b)) THEN
IF (ieor(sym(p3b),sym(h4b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p3b,h4b,p3b_1,h4b_1)
CALL TCE_RESTRICTED_4(h6b,h4b,p5b,p3b,h6b_2,h4b_2,p5b_2,p3b_2)
dim_common = range(p3b) * range(h4b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = range(h6b) * range(p5b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h4b_1 - 1 + noab * (p3b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p3b),range(h4b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h4b <= h6b) .and. (p3b <= p5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (h6b_2 - 1 + (noab+nvab) * (h4b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h4b),range(h6b),range(p3b),range(p5b),4,2,1,3,1.0d0)
END IF
IF ((h4b <= h6b) .and. (p5b < p3b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - 1 + (noab+nvab) * (p5b_2 - 1 + (noab+nvab) * (h6b_2 - 1 + (noab+nvab) * (h4b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h4b),range(h6b),range(p5b),range(p3b),3,2,1,4,-1.0d0)
END IF
IF ((h6b < h4b) .and. (p3b <= p5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (h4b_2 - 1 + (noab+nvab) * (h6b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h6b),range(h4b),range(p3b),range(p5b),4,1,2,3,-1.0d0)
END IF
IF ((h6b < h4b) .and. (p5b < p3b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - 1 + (noab+nvab) * (p5b_2 - 1 + (noab+nvab) * (h4b_2 - 1 + (noab+nvab) * (h6b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h6b),range(h4b),range(p5b),range(p3b),3,1,2,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(p5b),range(h6b),2,1,1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p5b - noab - 1 + nvab * (h6b - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdtq_e_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( )_vt + = 1/4 * Sum ( h3 h4 p1 p2 ) * t ( p1 p2 h3 h4 )_t * v ( h3 h4 p1 p2 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: dimc
INTEGER :: p1b
INTEGER :: p2b
INTEGER :: h3b
INTEGER :: h4b
INTEGER :: p1b_1
INTEGER :: p2b_1
INTEGER :: h3b_1
INTEGER :: h4b_1
INTEGER :: h3b_2
INTEGER :: h4b_2
INTEGER :: p1b_2
INTEGER :: p2b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsuperp(2)
INTEGER :: isuperp
INTEGER :: nsubh(2)
INTEGER :: isubh
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
IF (next == count) THEN
IF (0 == ieor(irrep_v,irrep_t)) THEN
dimc = 1
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p1b = noab+1,noab+nvab
DO p2b = p1b,noab+nvab
DO h3b = 1,noab
DO h4b = h3b,noab
IF (spin(p1b)+spin(p2b) == spin(h3b)+spin(h4b)) THEN
IF (ieor(sym(p1b),ieor(sym(p2b),ieor(sym(h3b),sym(h4b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p1b,p2b,h3b,h4b,p1b_1,p2b_1,h3b_1,h4b_1)
CALL TCE_RESTRICTED_4(h3b,h4b,p1b,p2b,h3b_2,h4b_2,p1b_2,p2b_2)
dim_common = range(p1b) * range(p2b) * range(h3b) * range(h4b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = 1
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h4b_1 - 1 + noab * (h3b_1 - 1 + noab * (p2b_1 - noab - 1 + nvab * (p1b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p1b),range(p2b),range(h3b),range(h4b),4,3,2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p2b_2 - 1 + (noab+nvab) * (p1b_2 - 1 + (noab+nvab) * (h4b_2 - 1 + (noab+nvab) * (h3b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h3b),range(h4b),range(p1b),range(p2b),2,1,4,3,1.0d0)
DEALLOCATE(b)
nsuperp(1) = 1
nsuperp(2) = 1
isuperp = 1
IF (p1b == p2b) THEN
nsuperp(isuperp) = nsuperp(isuperp) + 1
ELSE
isuperp = isuperp + 1
END IF
nsubh(1) = 1
nsubh(2) = 1
isubh = 1
IF (h3b == h4b) THEN
nsubh(isubh) = nsubh(isubh) + 1
ELSE
isubh = isubh + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,4.0d0/FACTORIAL(nsuperp(1))/FACTORIAL(nsuperp(2))/FACTORIAL(nsubh(1))/FACTORIAL(n&
&subh(2)),a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_0(c_sort,c,1.0d0/4.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,0)
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
