SUBROUTINE ccsdt_t1(d_f1,d_i0,d_t1,d_t2,d_t3,d_v2,f1_offset,i0_offset,t1_offset,t2_offset,t3_offset,v2_offset)
!$Id$
!This is a Fortran90 program generated by Tensor Contraction Engine v.1.0
!
!
!i0 ( p2 h1 )_f + = 1 * f ( p2 h1 )_f
!i0 ( p2 h1 )_tf + = -1 * Sum ( h7 ) * t ( p2 h7 )_t * i1 ( h7 h1 )_f
!    i1 ( h7 h1 )_f + = 1 * f ( h7 h1 )_f
!    i1 ( h7 h1 )_ft + = 1 * Sum ( p3 ) * t ( p3 h1 )_t * i2 ( h7 p3 )_f
!        i2 ( h7 p3 )_f + = 1 * f ( h7 p3 )_f
!        i2 ( h7 p3 )_vt + = -1 * Sum ( h6 p5 ) * t ( p5 h6 )_t * v ( h6 h7 p3 p5 )_v
!    i1 ( h7 h1 )_vt + = -1 * Sum ( h5 p4 ) * t ( p4 h5 )_t * v ( h5 h7 h1 p4 )_v
!    i1 ( h7 h1 )_vt + = -1/2 * Sum ( h5 p3 p4 ) * t ( p3 p4 h1 h5 )_t * v ( h5 h7 p3 p4 )_v
!i0 ( p2 h1 )_tf + = 1 * Sum ( p3 ) * t ( p3 h1 )_t * i1 ( p2 p3 )_f
!    i1 ( p2 p3 )_f + = 1 * f ( p2 p3 )_f
!    i1 ( p2 p3 )_vt + = -1 * Sum ( h5 p4 ) * t ( p4 h5 )_t * v ( h5 p2 p3 p4 )_v
!i0 ( p2 h1 )_vt + = -1 * Sum ( h4 p3 ) * t ( p3 h4 )_t * v ( h4 p2 h1 p3 )_v
!i0 ( p2 h1 )_tf + = 1 * Sum ( p7 h8 ) * t ( p2 p7 h1 h8 )_t * i1 ( h8 p7 )_f
!    i1 ( h8 p7 )_f + = 1 * f ( h8 p7 )_f
!    i1 ( h8 p7 )_vt + = 1 * Sum ( h6 p5 ) * t ( p5 h6 )_t * v ( h6 h8 p5 p7 )_v
!i0 ( p2 h1 )_vt + = -1/2 * Sum ( h4 h5 p3 ) * t ( p2 p3 h4 h5 )_t * i1 ( h4 h5 h1 p3 )_v
!    i1 ( h4 h5 h1 p3 )_v + = 1 * v ( h4 h5 h1 p3 )_v
!    i1 ( h4 h5 h1 p3 )_vt + = -1 * Sum ( p6 ) * t ( p6 h1 )_t * v ( h4 h5 p3 p6 )_v
!i0 ( p2 h1 )_vt + = -1/2 * Sum ( h5 p3 p4 ) * t ( p3 p4 h1 h5 )_t * v ( h5 p2 p3 p4 )_v
!i0 ( p2 h1 )_vt + = 1/4 * Sum ( h5 h6 p3 p4 ) * t ( p2 p3 p4 h1 h5 h6 )_t * v ( h5 h6 p3 p4 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_i0
INTEGER :: d_f1
INTEGER :: d_t1
INTEGER :: d_i1
INTEGER :: d_v2
INTEGER :: d_t2
INTEGER :: d_t3
INTEGER :: length
INTEGER :: d_i2
INTEGER :: i0_offset(*)
INTEGER :: f1_offset(*)
INTEGER :: t1_offset(*)
INTEGER :: v2_offset(*)
INTEGER :: t2_offset(*)
INTEGER :: t3_offset(*)
INTEGER, ALLOCATABLE :: i1_offset(:)
INTEGER, ALLOCATABLE :: i2_offset(:)
REAL*8 :: size_i1
REAL*8 :: size_i2
CHARACTER(LEN=255) :: filename
CALL ccsdt_t1_1(d_f1,f1_offset,d_i0,i0_offset)
CALL OFFSET_ccsdt_t1_2_1_a(length)
ALLOCATE(i1_offset(length*2+1))
CALL OFFSET_ccsdt_t1_2_1_b(i1_offset,size_i1,length)
CALL UT_TCE_FILENAME('ccsdt_t1_2_1_i1',filename)
CALL CREATEFILE(filename,d_i1,size_i1)
CALL ccsdt_t1_2_1(d_f1,f1_offset,d_i1,i1_offset)
CALL OFFSET_ccsdt_t1_2_2_1_a(length)
ALLOCATE(i2_offset(length*2+1))
CALL OFFSET_ccsdt_t1_2_2_1_b(i2_offset,size_i2,length)
CALL UT_TCE_FILENAME('ccsdt_t1_2_2_1_i2',filename)
CALL CREATEFILE(filename,d_i2,size_i2)
CALL ccsdt_t1_2_2_1(d_f1,f1_offset,d_i2,i2_offset)
CALL ccsdt_t1_2_2_2(d_t1,t1_offset,d_v2,v2_offset,d_i2,i2_offset)
CALL RECONCILEFILE(d_i2,size_i2)
CALL ccsdt_t1_2_2(d_t1,t1_offset,d_i2,i2_offset,d_i1,i1_offset)
CALL DELETEFILE(d_i2)
DEALLOCATE(i2_offset)
CALL ccsdt_t1_2_3(d_t1,t1_offset,d_v2,v2_offset,d_i1,i1_offset)
CALL ccsdt_t1_2_4(d_t2,t2_offset,d_v2,v2_offset,d_i1,i1_offset)
CALL RECONCILEFILE(d_i1,size_i1)
CALL ccsdt_t1_2(d_t1,t1_offset,d_i1,i1_offset,d_i0,i0_offset)
CALL DELETEFILE(d_i1)
DEALLOCATE(i1_offset)
CALL OFFSET_ccsdt_t1_3_1_a(length)
ALLOCATE(i1_offset(length*2+1))
CALL OFFSET_ccsdt_t1_3_1_b(i1_offset,size_i1,length)
CALL UT_TCE_FILENAME('ccsdt_t1_3_1_i1',filename)
CALL CREATEFILE(filename,d_i1,size_i1)
CALL ccsdt_t1_3_1(d_f1,f1_offset,d_i1,i1_offset)
CALL ccsdt_t1_3_2(d_t1,t1_offset,d_v2,v2_offset,d_i1,i1_offset)
CALL RECONCILEFILE(d_i1,size_i1)
CALL ccsdt_t1_3(d_t1,t1_offset,d_i1,i1_offset,d_i0,i0_offset)
CALL DELETEFILE(d_i1)
DEALLOCATE(i1_offset)
CALL ccsdt_t1_4(d_t1,t1_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL OFFSET_ccsdt_t1_5_1_a(length)
ALLOCATE(i1_offset(length*2+1))
CALL OFFSET_ccsdt_t1_5_1_b(i1_offset,size_i1,length)
CALL UT_TCE_FILENAME('ccsdt_t1_5_1_i1',filename)
CALL CREATEFILE(filename,d_i1,size_i1)
CALL ccsdt_t1_5_1(d_f1,f1_offset,d_i1,i1_offset)
CALL ccsdt_t1_5_2(d_t1,t1_offset,d_v2,v2_offset,d_i1,i1_offset)
CALL RECONCILEFILE(d_i1,size_i1)
CALL ccsdt_t1_5(d_t2,t2_offset,d_i1,i1_offset,d_i0,i0_offset)
CALL DELETEFILE(d_i1)
DEALLOCATE(i1_offset)
CALL OFFSET_ccsdt_t1_6_1_a(length)
ALLOCATE(i1_offset(length*2+1))
CALL OFFSET_ccsdt_t1_6_1_b(i1_offset,size_i1,length)
CALL UT_TCE_FILENAME('ccsdt_t1_6_1_i1',filename)
CALL CREATEFILE(filename,d_i1,size_i1)
CALL ccsdt_t1_6_1(d_v2,v2_offset,d_i1,i1_offset)
CALL ccsdt_t1_6_2(d_t1,t1_offset,d_v2,v2_offset,d_i1,i1_offset)
CALL RECONCILEFILE(d_i1,size_i1)
CALL ccsdt_t1_6(d_t2,t2_offset,d_i1,i1_offset,d_i0,i0_offset)
CALL DELETEFILE(d_i1)
DEALLOCATE(i1_offset)
CALL ccsdt_t1_7(d_t2,t2_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL ccsdt_t1_8(d_t3,t3_offset,d_v2,v2_offset,d_i0,i0_offset)
RETURN
END
SUBROUTINE ccsdt_t1_1(d_a,a_offset,d_c,c_offset)
!i0 ( p2 h1 )_f + = 1 * f ( p2 h1 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p2b_1
INTEGER :: h1b_1
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: a_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(h1b) /= 4)) THEN
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == irrep_f) THEN
dimc = range(p2b) * range(h1b)
CALL TCE_RESTRICTED_2(p2b,h1b,p2b_1,h1b_1)
dim_common = 1
dima_sort = range(p2b) * range(h1b)
dima = dim_common * dima_sort
IF (dima > 0) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + (noab+nvab) * (p2b_1 - 1)))
CALL TCE_SORT_2(a,a_sort,range(p2b),range(h1b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(c(dimc))
CALL TCE_SORT_2(a_sort,c,range(h1b),range(p2b),2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p2 h1 )_tf + = -1 * Sum ( h7 ) * t ( p2 h7 )_t * i1 ( h7 h1 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: h7b
INTEGER :: p2b_1
INTEGER :: h7b_1
INTEGER :: h7b_2
INTEGER :: h1b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(h1b) /= 4)) THEN
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == ieor(irrep_t,irrep_f)) THEN
dimc = range(p2b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO h7b = 1,noab
IF (spin(p2b) == spin(h7b)) THEN
IF (ieor(sym(p2b),sym(h7b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p2b,h7b,p2b_1,h7b_1)
CALL TCE_RESTRICTED_2(h7b,h1b,h7b_2,h1b_2)
dim_common = range(h7b)
dima_sort = range(p2b)
dima = dim_common * dima_sort
dimb_sort = range(h1b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h7b_1 - 1 + noab * (p2b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p2b),range(h7b),1,2,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h1b_2 - 1 + noab * (h7b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(h7b),range(h1b),2,1,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(h1b),range(p2b),2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_2_1(d_a,a_offset,d_c,c_offset)
!i1 ( h7 h1 )_f + = 1 * f ( h7 h1 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h7b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: h7b_1
INTEGER :: h1b_1
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: a_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h7b = 1,noab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(h1b) /= 4)) THEN
IF (spin(h7b) == spin(h1b)) THEN
IF (ieor(sym(h7b),sym(h1b)) == irrep_f) THEN
dimc = range(h7b) * range(h1b)
CALL TCE_RESTRICTED_2(h7b,h1b,h7b_1,h1b_1)
dim_common = 1
dima_sort = range(h7b) * range(h1b)
dima = dim_common * dima_sort
IF (dima > 0) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + (noab+nvab) * (h7b_1 - 1)))
CALL TCE_SORT_2(a,a_sort,range(h7b),range(h1b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(c(dimc))
CALL TCE_SORT_2(a_sort,c,range(h1b),range(h7b),2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h7b - 1)))
DEALLOCATE(c)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_2_1_b(a_offset,size,length)
!i1 ( h7 h1 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: addr
INTEGER :: h7b
INTEGER :: h1b
INTEGER :: a_offset(*)
REAL*8 :: size
a_offset(1) = length
addr = 0
size = 0.0d0
DO h7b = 1,noab
DO h1b = 1,noab
IF (spin(h7b) == spin(h1b)) THEN
IF (ieor(sym(h7b),sym(h1b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(h1b) /= 4)) THEN
addr = addr + 1
a_offset(addr+1) = h1b - 1 + noab * (h7b - 1)
a_offset(length+addr+1) = size
size = size + dfloat(range(h7b)) * dfloat(range(h1b))
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_2_1_a(length)
!i1 ( h7 h1 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: h7b
INTEGER :: h1b
length = 0
DO h7b = 1,noab
DO h1b = 1,noab
IF (spin(h7b) == spin(h1b)) THEN
IF (ieor(sym(h7b),sym(h1b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(h1b) /= 4)) THEN
length = length + 1
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE ccsdt_t1_2_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i1 ( h7 h1 )_ft + = 1 * Sum ( p3 ) * t ( p3 h1 )_t * i2 ( h7 p3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h7b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p3b
INTEGER :: p3b_1
INTEGER :: h1b_1
INTEGER :: h7b_2
INTEGER :: p3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h7b = 1,noab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(h1b) /= 4)) THEN
IF (spin(h7b) == spin(h1b)) THEN
IF (ieor(sym(h7b),sym(h1b)) == ieor(irrep_f,irrep_t)) THEN
dimc = range(h7b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p3b = noab+1,noab+nvab
IF (spin(p3b) == spin(h1b)) THEN
IF (ieor(sym(p3b),sym(h1b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p3b,h1b,p3b_1,h1b_1)
CALL TCE_RESTRICTED_2(h7b,p3b,h7b_2,p3b_2)
dim_common = range(p3b)
dima_sort = range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(h7b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (p3b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p3b),range(h1b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - noab - 1 + nvab * (h7b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(h7b),range(p3b),1,2,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(h7b),range(h1b),1,2,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h7b - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_2_2_1(d_a,a_offset,d_c,c_offset)
!i2 ( h7 p3 )_f + = 1 * f ( h7 p3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h7b
INTEGER :: p3b
INTEGER :: dimc
INTEGER :: h7b_1
INTEGER :: p3b_1
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: a_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h7b = 1,noab
DO p3b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(p3b) /= 4)) THEN
IF (spin(h7b) == spin(p3b)) THEN
IF (ieor(sym(h7b),sym(p3b)) == irrep_f) THEN
dimc = range(h7b) * range(p3b)
CALL TCE_RESTRICTED_2(h7b,p3b,h7b_1,p3b_1)
dim_common = 1
dima_sort = range(h7b) * range(p3b)
dima = dim_common * dima_sort
IF (dima > 0) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(p3b_1 - 1 + (noab+nvab) * (h7b_1 - 1)))
CALL TCE_SORT_2(a,a_sort,range(h7b),range(p3b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(c(dimc))
CALL TCE_SORT_2(a_sort,c,range(p3b),range(h7b),2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p3b - noab - 1 + nvab * (h7b - 1)))
DEALLOCATE(c)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_2_2_1_b(a_offset,size,length)
!i2 ( h7 p3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: addr
INTEGER :: h7b
INTEGER :: p3b
INTEGER :: a_offset(*)
REAL*8 :: size
a_offset(1) = length
addr = 0
size = 0.0d0
DO h7b = 1,noab
DO p3b = noab+1,noab+nvab
IF (spin(h7b) == spin(p3b)) THEN
IF (ieor(sym(h7b),sym(p3b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(p3b) /= 4)) THEN
addr = addr + 1
a_offset(addr+1) = p3b - noab - 1 + nvab * (h7b - 1)
a_offset(length+addr+1) = size
size = size + dfloat(range(h7b)) * dfloat(range(p3b))
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_2_2_1_a(length)
!i2 ( h7 p3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: h7b
INTEGER :: p3b
length = 0
DO h7b = 1,noab
DO p3b = noab+1,noab+nvab
IF (spin(h7b) == spin(p3b)) THEN
IF (ieor(sym(h7b),sym(p3b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(p3b) /= 4)) THEN
length = length + 1
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE ccsdt_t1_2_2_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i2 ( h7 p3 )_vt + = -1 * Sum ( h6 p5 ) * t ( p5 h6 )_t * v ( h6 h7 p3 p5 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h7b
INTEGER :: p3b
INTEGER :: dimc
INTEGER :: p5b
INTEGER :: h6b
INTEGER :: p5b_1
INTEGER :: h6b_1
INTEGER :: h7b_2
INTEGER :: h6b_2
INTEGER :: p3b_2
INTEGER :: p5b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h7b = 1,noab
DO p3b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(p3b) /= 4)) THEN
IF (spin(h7b) == spin(p3b)) THEN
IF (ieor(sym(h7b),sym(p3b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(h7b) * range(p3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p5b = noab+1,noab+nvab
DO h6b = 1,noab
IF (spin(p5b) == spin(h6b)) THEN
IF (ieor(sym(p5b),sym(h6b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p5b,h6b,p5b_1,h6b_1)
CALL TCE_RESTRICTED_4(h7b,h6b,p3b,p5b,h7b_2,h6b_2,p3b_2,p5b_2)
dim_common = range(p5b) * range(h6b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = range(h7b) * range(p3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (p5b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p5b),range(h6b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h6b <= h7b) .and. (p5b < p3b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - 1 + (noab+nvab) * (p5b_2 - 1 + (noab+nvab) * (h7b_2 - 1 + (noab+nvab) * (h6b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h6b),range(h7b),range(p5b),range(p3b),4,2,1,3,-1.0d0)
END IF
IF ((h6b <= h7b) .and. (p3b <= p5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (h7b_2 - 1 + (noab+nvab) * (h6b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h6b),range(h7b),range(p3b),range(p5b),3,2,1,4,1.0d0)
END IF
IF ((h7b < h6b) .and. (p5b < p3b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - 1 + (noab+nvab) * (p5b_2 - 1 + (noab+nvab) * (h6b_2 - 1 + (noab+nvab) * (h7b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h7b),range(h6b),range(p5b),range(p3b),4,1,2,3,1.0d0)
END IF
IF ((h7b < h6b) .and. (p3b <= p5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (h6b_2 - 1 + (noab+nvab) * (h7b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h7b),range(h6b),range(p3b),range(p5b),3,1,2,4,-1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(p3b),range(h7b),2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p3b - noab - 1 + nvab * (h7b - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_2_3(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i1 ( h7 h1 )_vt + = -1 * Sum ( h5 p4 ) * t ( p4 h5 )_t * v ( h5 h7 h1 p4 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h7b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p4b
INTEGER :: h5b
INTEGER :: p4b_1
INTEGER :: h5b_1
INTEGER :: h7b_2
INTEGER :: h5b_2
INTEGER :: h1b_2
INTEGER :: p4b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h7b = 1,noab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(h1b) /= 4)) THEN
IF (spin(h7b) == spin(h1b)) THEN
IF (ieor(sym(h7b),sym(h1b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(h7b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p4b = noab+1,noab+nvab
DO h5b = 1,noab
IF (spin(p4b) == spin(h5b)) THEN
IF (ieor(sym(p4b),sym(h5b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p4b,h5b,p4b_1,h5b_1)
CALL TCE_RESTRICTED_4(h7b,h5b,h1b,p4b,h7b_2,h5b_2,h1b_2,p4b_2)
dim_common = range(p4b) * range(h5b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = range(h7b) * range(h1b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h5b_1 - 1 + noab * (p4b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p4b),range(h5b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h5b <= h7b) .and. (h1b <= p4b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p4b_2 - 1 + (noab+nvab) * (h1b_2 - 1 + (noab+nvab) * (h7b_2 - 1 + (noab+nvab) * (h5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h5b),range(h7b),range(h1b),range(p4b),3,2,1,4,1.0d0)
END IF
IF ((h7b < h5b) .and. (h1b <= p4b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p4b_2 - 1 + (noab+nvab) * (h1b_2 - 1 + (noab+nvab) * (h5b_2 - 1 + (noab+nvab) * (h7b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h7b),range(h5b),range(h1b),range(p4b),3,1,2,4,-1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(h1b),range(h7b),2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h7b - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_2_4(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i1 ( h7 h1 )_vt + = -1/2 * Sum ( h5 p3 p4 ) * t ( p3 p4 h1 h5 )_t * v ( h5 h7 p3 p4 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h7b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h5b
INTEGER :: p3b_1
INTEGER :: p4b_1
INTEGER :: h1b_1
INTEGER :: h5b_1
INTEGER :: h7b_2
INTEGER :: h5b_2
INTEGER :: p3b_2
INTEGER :: p4b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsuperp(2)
INTEGER :: isuperp
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h7b = 1,noab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h7b)+spin(h1b) /= 4)) THEN
IF (spin(h7b) == spin(h1b)) THEN
IF (ieor(sym(h7b),sym(h1b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(h7b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p3b = noab+1,noab+nvab
DO p4b = p3b,noab+nvab
DO h5b = 1,noab
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h5b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h5b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p3b,p4b,h1b,h5b,p3b_1,p4b_1,h1b_1,h5b_1)
CALL TCE_RESTRICTED_4(h7b,h5b,p3b,p4b,h7b_2,h5b_2,p3b_2,p4b_2)
dim_common = range(p3b) * range(p4b) * range(h5b)
dima_sort = range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(h7b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((h5b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h5b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p4b),range(h5b),range(h1b),4,3,2,1,-1.0d0)
END IF
IF ((h1b <= h5b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h5b_1 - 1 + noab * (h1b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p4b),range(h1b),range(h5b),3,4,2,1,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h5b <= h7b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p4b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (h7b_2 - 1 + (noab+nvab) * (h5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h5b),range(h7b),range(p3b),range(p4b),2,1,4,3,1.0d0)
END IF
IF ((h7b < h5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p4b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (h5b_2 - 1 + (noab+nvab) * (h7b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h7b),range(h5b),range(p3b),range(p4b),1,2,4,3,-1.0d0)
END IF
DEALLOCATE(b)
nsuperp(1) = 1
nsuperp(2) = 1
isuperp = 1
IF (p3b == p4b) THEN
nsuperp(isuperp) = nsuperp(isuperp) + 1
ELSE
isuperp = isuperp + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,2.0d0/FACTORIAL(nsuperp(1))/FACTORIAL(nsuperp(2)),a_sort,dim_common,b_sort,dim_co&
&mmon,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(h7b),range(h1b),1,2,-1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h7b - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_3(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p2 h1 )_tf + = 1 * Sum ( p3 ) * t ( p3 h1 )_t * i1 ( p2 p3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p3b
INTEGER :: p3b_1
INTEGER :: h1b_1
INTEGER :: p2b_2
INTEGER :: p3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(h1b) /= 4)) THEN
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == ieor(irrep_t,irrep_f)) THEN
dimc = range(p2b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p3b = noab+1,noab+nvab
IF (spin(p3b) == spin(h1b)) THEN
IF (ieor(sym(p3b),sym(h1b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p3b,h1b,p3b_1,h1b_1)
CALL TCE_RESTRICTED_2(p2b,p3b,p2b_2,p3b_2)
dim_common = range(p3b)
dima_sort = range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(p2b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (p3b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p3b),range(h1b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - noab - 1 + nvab * (p2b_2 - noab - 1)))
CALL TCE_SORT_2(b,b_sort,range(p2b),range(p3b),1,2,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(p2b),range(h1b),1,2,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_3_1(d_a,a_offset,d_c,c_offset)
!i1 ( p2 p3 )_f + = 1 * f ( p2 p3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: p3b
INTEGER :: dimc
INTEGER :: p2b_1
INTEGER :: p3b_1
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: a_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO p3b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(p3b) /= 4)) THEN
IF (spin(p2b) == spin(p3b)) THEN
IF (ieor(sym(p2b),sym(p3b)) == irrep_f) THEN
dimc = range(p2b) * range(p3b)
CALL TCE_RESTRICTED_2(p2b,p3b,p2b_1,p3b_1)
dim_common = 1
dima_sort = range(p2b) * range(p3b)
dima = dim_common * dima_sort
IF (dima > 0) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(p3b_1 - 1 + (noab+nvab) * (p2b_1 - 1)))
CALL TCE_SORT_2(a,a_sort,range(p2b),range(p3b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(c(dimc))
CALL TCE_SORT_2(a_sort,c,range(p3b),range(p2b),2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p3b - noab - 1 + nvab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_3_1_b(a_offset,size,length)
!i1 ( p2 p3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: addr
INTEGER :: p2b
INTEGER :: p3b
INTEGER :: a_offset(*)
REAL*8 :: size
a_offset(1) = length
addr = 0
size = 0.0d0
DO p2b = noab+1,noab+nvab
DO p3b = noab+1,noab+nvab
IF (spin(p2b) == spin(p3b)) THEN
IF (ieor(sym(p2b),sym(p3b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(p3b) /= 4)) THEN
addr = addr + 1
a_offset(addr+1) = p3b - noab - 1 + nvab * (p2b - noab - 1)
a_offset(length+addr+1) = size
size = size + dfloat(range(p2b)) * dfloat(range(p3b))
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_3_1_a(length)
!i1 ( p2 p3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: p2b
INTEGER :: p3b
length = 0
DO p2b = noab+1,noab+nvab
DO p3b = noab+1,noab+nvab
IF (spin(p2b) == spin(p3b)) THEN
IF (ieor(sym(p2b),sym(p3b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(p3b) /= 4)) THEN
length = length + 1
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE ccsdt_t1_3_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i1 ( p2 p3 )_vt + = -1 * Sum ( h5 p4 ) * t ( p4 h5 )_t * v ( h5 p2 p3 p4 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: p3b
INTEGER :: dimc
INTEGER :: p4b
INTEGER :: h5b
INTEGER :: p4b_1
INTEGER :: h5b_1
INTEGER :: p2b_2
INTEGER :: h5b_2
INTEGER :: p3b_2
INTEGER :: p4b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO p3b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(p3b) /= 4)) THEN
IF (spin(p2b) == spin(p3b)) THEN
IF (ieor(sym(p2b),sym(p3b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p2b) * range(p3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p4b = noab+1,noab+nvab
DO h5b = 1,noab
IF (spin(p4b) == spin(h5b)) THEN
IF (ieor(sym(p4b),sym(h5b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p4b,h5b,p4b_1,h5b_1)
CALL TCE_RESTRICTED_4(p2b,h5b,p3b,p4b,p2b_2,h5b_2,p3b_2,p4b_2)
dim_common = range(p4b) * range(h5b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = range(p2b) * range(p3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h5b_1 - 1 + noab * (p4b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p4b),range(h5b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h5b <= p2b) .and. (p4b < p3b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - 1 + (noab+nvab) * (p4b_2 - 1 + (noab+nvab) * (p2b_2 - 1 + (noab+nvab) * (h5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h5b),range(p2b),range(p4b),range(p3b),4,2,1,3,-1.0d0)
END IF
IF ((h5b <= p2b) .and. (p3b <= p4b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p4b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (p2b_2 - 1 + (noab+nvab) * (h5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h5b),range(p2b),range(p3b),range(p4b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(p3b),range(p2b),2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p3b - noab - 1 + nvab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_4(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p2 h1 )_vt + = -1 * Sum ( h4 p3 ) * t ( p3 h4 )_t * v ( h4 p2 h1 p3 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p3b
INTEGER :: h4b
INTEGER :: p3b_1
INTEGER :: h4b_1
INTEGER :: p2b_2
INTEGER :: h4b_2
INTEGER :: h1b_2
INTEGER :: p3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(h1b) /= 4)) THEN
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p2b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p3b = noab+1,noab+nvab
DO h4b = 1,noab
IF (spin(p3b) == spin(h4b)) THEN
IF (ieor(sym(p3b),sym(h4b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p3b,h4b,p3b_1,h4b_1)
CALL TCE_RESTRICTED_4(p2b,h4b,h1b,p3b,p2b_2,h4b_2,h1b_2,p3b_2)
dim_common = range(p3b) * range(h4b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = range(p2b) * range(h1b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h4b_1 - 1 + noab * (p3b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p3b),range(h4b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h4b <= p2b) .and. (h1b <= p3b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - 1 + (noab+nvab) * (h1b_2 - 1 + (noab+nvab) * (p2b_2 - 1 + (noab+nvab) * (h4b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h4b),range(p2b),range(h1b),range(p3b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(h1b),range(p2b),2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_5(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p2 h1 )_tf + = 1 * Sum ( p7 h8 ) * t ( p2 p7 h1 h8 )_t * i1 ( h8 p7 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p7b
INTEGER :: h8b
INTEGER :: p2b_1
INTEGER :: p7b_1
INTEGER :: h1b_1
INTEGER :: h8b_1
INTEGER :: h8b_2
INTEGER :: p7b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(h1b) /= 4)) THEN
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == ieor(irrep_t,irrep_f)) THEN
dimc = range(p2b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p7b = noab+1,noab+nvab
DO h8b = 1,noab
IF (spin(p2b)+spin(p7b) == spin(h1b)+spin(h8b)) THEN
IF (ieor(sym(p2b),ieor(sym(p7b),ieor(sym(h1b),sym(h8b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p2b,p7b,h1b,h8b,p2b_1,p7b_1,h1b_1,h8b_1)
CALL TCE_RESTRICTED_2(h8b,p7b,h8b_2,p7b_2)
dim_common = range(p7b) * range(h8b)
dima_sort = range(p2b) * range(h1b)
dima = dim_common * dima_sort
dimb_sort = 1
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p7b < p2b) .and. (h8b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h8b_1 - 1 + noab * (p2b_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p7b),range(p2b),range(h8b),range(h1b),4,2,3,1,1.0d0)
END IF
IF ((p7b < p2b) .and. (h1b <= h8b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h8b_1 - 1 + noab * (h1b_1 - 1 + noab * (p2b_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p7b),range(p2b),range(h1b),range(h8b),3,2,4,1,-1.0d0)
END IF
IF ((p2b <= p7b) .and. (h8b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h8b_1 - 1 + noab * (p7b_1 - noab - 1 + nvab * (p2b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p2b),range(p7b),range(h8b),range(h1b),4,1,3,2,-1.0d0)
END IF
IF ((p2b <= p7b) .and. (h1b <= h8b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h8b_1 - 1 + noab * (h1b_1 - 1 + noab * (p7b_1 - noab - 1 + nvab * (p2b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p2b),range(p7b),range(h1b),range(h8b),3,1,4,2,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p7b_2 - noab - 1 + nvab * (h8b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(h8b),range(p7b),1,2,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(h1b),range(p2b),2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_5_1(d_a,a_offset,d_c,c_offset)
!i1 ( h8 p7 )_f + = 1 * f ( h8 p7 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h8b
INTEGER :: p7b
INTEGER :: dimc
INTEGER :: h8b_1
INTEGER :: p7b_1
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: a_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h8b = 1,noab
DO p7b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h8b)+spin(p7b) /= 4)) THEN
IF (spin(h8b) == spin(p7b)) THEN
IF (ieor(sym(h8b),sym(p7b)) == irrep_f) THEN
dimc = range(h8b) * range(p7b)
CALL TCE_RESTRICTED_2(h8b,p7b,h8b_1,p7b_1)
dim_common = 1
dima_sort = range(h8b) * range(p7b)
dima = dim_common * dima_sort
IF (dima > 0) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(p7b_1 - 1 + (noab+nvab) * (h8b_1 - 1)))
CALL TCE_SORT_2(a,a_sort,range(h8b),range(p7b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(c(dimc))
CALL TCE_SORT_2(a_sort,c,range(p7b),range(h8b),2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p7b - noab - 1 + nvab * (h8b - 1)))
DEALLOCATE(c)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_5_1_b(a_offset,size,length)
!i1 ( h8 p7 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: addr
INTEGER :: h8b
INTEGER :: p7b
INTEGER :: a_offset(*)
REAL*8 :: size
a_offset(1) = length
addr = 0
size = 0.0d0
DO h8b = 1,noab
DO p7b = noab+1,noab+nvab
IF (spin(h8b) == spin(p7b)) THEN
IF (ieor(sym(h8b),sym(p7b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(h8b)+spin(p7b) /= 4)) THEN
addr = addr + 1
a_offset(addr+1) = p7b - noab - 1 + nvab * (h8b - 1)
a_offset(length+addr+1) = size
size = size + dfloat(range(h8b)) * dfloat(range(p7b))
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_5_1_a(length)
!i1 ( h8 p7 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: h8b
INTEGER :: p7b
length = 0
DO h8b = 1,noab
DO p7b = noab+1,noab+nvab
IF (spin(h8b) == spin(p7b)) THEN
IF (ieor(sym(h8b),sym(p7b)) == irrep_f) THEN
IF ((.not.restricted).or.(spin(h8b)+spin(p7b) /= 4)) THEN
length = length + 1
END IF
END IF
END IF
END DO
END DO
RETURN
END
SUBROUTINE ccsdt_t1_5_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i1 ( h8 p7 )_vt + = 1 * Sum ( h6 p5 ) * t ( p5 h6 )_t * v ( h6 h8 p5 p7 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h8b
INTEGER :: p7b
INTEGER :: dimc
INTEGER :: p5b
INTEGER :: h6b
INTEGER :: p5b_1
INTEGER :: h6b_1
INTEGER :: h8b_2
INTEGER :: h6b_2
INTEGER :: p7b_2
INTEGER :: p5b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h8b = 1,noab
DO p7b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h8b)+spin(p7b) /= 4)) THEN
IF (spin(h8b) == spin(p7b)) THEN
IF (ieor(sym(h8b),sym(p7b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(h8b) * range(p7b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p5b = noab+1,noab+nvab
DO h6b = 1,noab
IF (spin(p5b) == spin(h6b)) THEN
IF (ieor(sym(p5b),sym(h6b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p5b,h6b,p5b_1,h6b_1)
CALL TCE_RESTRICTED_4(h8b,h6b,p7b,p5b,h8b_2,h6b_2,p7b_2,p5b_2)
dim_common = range(p5b) * range(h6b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = range(h8b) * range(p7b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (p5b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p5b),range(h6b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h6b <= h8b) .and. (p5b <= p7b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p7b_2 - 1 + (noab+nvab) * (p5b_2 - 1 + (noab+nvab) * (h8b_2 - 1 + (noab+nvab) * (h6b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h6b),range(h8b),range(p5b),range(p7b),4,2,1,3,1.0d0)
END IF
IF ((h6b <= h8b) .and. (p7b < p5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (p7b_2 - 1 + (noab+nvab) * (h8b_2 - 1 + (noab+nvab) * (h6b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h6b),range(h8b),range(p7b),range(p5b),3,2,1,4,-1.0d0)
END IF
IF ((h8b < h6b) .and. (p5b <= p7b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p7b_2 - 1 + (noab+nvab) * (p5b_2 - 1 + (noab+nvab) * (h6b_2 - 1 + (noab+nvab) * (h8b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h8b),range(h6b),range(p5b),range(p7b),4,1,2,3,-1.0d0)
END IF
IF ((h8b < h6b) .and. (p7b < p5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (p7b_2 - 1 + (noab+nvab) * (h6b_2 - 1 + (noab+nvab) * (h8b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h8b),range(h6b),range(p7b),range(p5b),3,1,2,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(p7b),range(h8b),2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p7b - noab - 1 + nvab * (h8b - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_6(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p2 h1 )_vt + = -1/2 * Sum ( h4 h5 p3 ) * t ( p2 p3 h4 h5 )_t * i1 ( h4 h5 h1 p3 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p3b
INTEGER :: h4b
INTEGER :: h5b
INTEGER :: p2b_1
INTEGER :: p3b_1
INTEGER :: h4b_1
INTEGER :: h5b_1
INTEGER :: h4b_2
INTEGER :: h5b_2
INTEGER :: h1b_2
INTEGER :: p3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsubh(2)
INTEGER :: isubh
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(h1b) /= 4)) THEN
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p2b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p3b = noab+1,noab+nvab
DO h4b = 1,noab
DO h5b = h4b,noab
IF (spin(p2b)+spin(p3b) == spin(h4b)+spin(h5b)) THEN
IF (ieor(sym(p2b),ieor(sym(p3b),ieor(sym(h4b),sym(h5b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p2b,p3b,h4b,h5b,p2b_1,p3b_1,h4b_1,h5b_1)
CALL TCE_RESTRICTED_4(h4b,h5b,h1b,p3b,h4b_2,h5b_2,h1b_2,p3b_2)
dim_common = range(p3b) * range(h4b) * range(h5b)
dima_sort = range(p2b)
dima = dim_common * dima_sort
dimb_sort = range(h1b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p3b < p2b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h5b_1 - 1 + noab * (h4b_1 - 1 + noab * (p2b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p2b),range(h4b),range(h5b),2,4,3,1,-1.0d0)
END IF
IF ((p2b <= p3b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h5b_1 - 1 + noab * (h4b_1 - 1 + noab * (p3b_1 - noab - 1 + nvab * (p2b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p2b),range(p3b),range(h4b),range(h5b),1,4,3,2,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - noab - 1 + nvab * (h1b_2 - 1 + noab * (h5b_2 - 1 + noab * (h4b_2 - 1)))))
CALL TCE_SORT_4(b,b_sort,range(h4b),range(h5b),range(h1b),range(p3b),3,2,1,4,1.0d0)
DEALLOCATE(b)
nsubh(1) = 1
nsubh(2) = 1
isubh = 1
IF (h4b == h5b) THEN
nsubh(isubh) = nsubh(isubh) + 1
ELSE
isubh = isubh + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,2.0d0/FACTORIAL(nsubh(1))/FACTORIAL(nsubh(2)),a_sort,dim_common,b_sort,dim_common&
&,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(h1b),range(p2b),2,1,-1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_6_1(d_a,a_offset,d_c,c_offset)
!i1 ( h4 h5 h1 p3 )_v + = 1 * v ( h4 h5 h1 p3 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h4b
INTEGER :: h5b
INTEGER :: h1b
INTEGER :: p3b
INTEGER :: dimc
INTEGER :: h4b_1
INTEGER :: h5b_1
INTEGER :: h1b_1
INTEGER :: p3b_1
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: a_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h4b = 1,noab
DO h5b = h4b,noab
DO h1b = 1,noab
DO p3b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h4b)+spin(h5b)+spin(h1b)+spin(p3b) /= 8)) THEN
IF (spin(h4b)+spin(h5b) == spin(h1b)+spin(p3b)) THEN
IF (ieor(sym(h4b),ieor(sym(h5b),ieor(sym(h1b),sym(p3b)))) == irrep_v) THEN
dimc = range(h4b) * range(h5b) * range(h1b) * range(p3b)
CALL TCE_RESTRICTED_4(h4b,h5b,h1b,p3b,h4b_1,h5b_1,h1b_1,p3b_1)
dim_common = 1
dima_sort = range(h4b) * range(h5b) * range(h1b) * range(p3b)
dima = dim_common * dima_sort
IF (dima > 0) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((h1b <= p3b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(p3b_1 - 1 + (noab+nvab) * (h1b_1 - 1 + (noab+nvab) * (h5b_1 - 1 + (noab+nvab) * (h4b_1 - 1&
&)))))
CALL TCE_SORT_4(a,a_sort,range(h4b),range(h5b),range(h1b),range(p3b),4,3,2,1,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(c(dimc))
CALL TCE_SORT_4(a_sort,c,range(p3b),range(h1b),range(h5b),range(h4b),4,3,2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p3b - noab - 1 + nvab * (h1b - 1 + noab * (h5b - 1 + noab * (h4b - 1)))))
DEALLOCATE(c)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_6_1_b(a_offset,size,length)
!i1 ( h4 h5 h1 p3 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: addr
INTEGER :: h4b
INTEGER :: h5b
INTEGER :: h1b
INTEGER :: p3b
INTEGER :: a_offset(*)
REAL*8 :: size
a_offset(1) = length
addr = 0
size = 0.0d0
DO h4b = 1,noab
DO h5b = h4b,noab
DO h1b = 1,noab
DO p3b = noab+1,noab+nvab
IF (spin(h4b)+spin(h5b) == spin(h1b)+spin(p3b)) THEN
IF (ieor(sym(h4b),ieor(sym(h5b),ieor(sym(h1b),sym(p3b)))) == irrep_v) THEN
IF ((.not.restricted).or.(spin(h4b)+spin(h5b)+spin(h1b)+spin(p3b) /= 8)) THEN
addr = addr + 1
a_offset(addr+1) = p3b - noab - 1 + nvab * (h1b - 1 + noab * (h5b - 1 + noab * (h4b - 1)))
a_offset(length+addr+1) = size
size = size + dfloat(range(h4b)) * dfloat(range(h5b)) * dfloat(range(h1b)) * dfloat(range(p3b))
END IF
END IF
END IF
END DO
END DO
END DO
END DO
RETURN
END
SUBROUTINE OFFSET_ccsdt_t1_6_1_a(length)
!i1 ( h4 h5 h1 p3 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: length
INTEGER :: h4b
INTEGER :: h5b
INTEGER :: h1b
INTEGER :: p3b
length = 0
DO h4b = 1,noab
DO h5b = h4b,noab
DO h1b = 1,noab
DO p3b = noab+1,noab+nvab
IF (spin(h4b)+spin(h5b) == spin(h1b)+spin(p3b)) THEN
IF (ieor(sym(h4b),ieor(sym(h5b),ieor(sym(h1b),sym(p3b)))) == irrep_v) THEN
IF ((.not.restricted).or.(spin(h4b)+spin(h5b)+spin(h1b)+spin(p3b) /= 8)) THEN
length = length + 1
END IF
END IF
END IF
END DO
END DO
END DO
END DO
RETURN
END
SUBROUTINE ccsdt_t1_6_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i1 ( h4 h5 h1 p3 )_vt + = -1 * Sum ( p6 ) * t ( p6 h1 )_t * v ( h4 h5 p3 p6 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: h4b
INTEGER :: h5b
INTEGER :: h1b
INTEGER :: p3b
INTEGER :: dimc
INTEGER :: p6b
INTEGER :: p6b_1
INTEGER :: h1b_1
INTEGER :: h4b_2
INTEGER :: h5b_2
INTEGER :: p3b_2
INTEGER :: p6b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO h4b = 1,noab
DO h5b = h4b,noab
DO h1b = 1,noab
DO p3b = noab+1,noab+nvab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(h4b)+spin(h5b)+spin(h1b)+spin(p3b) /= 8)) THEN
IF (spin(h4b)+spin(h5b) == spin(h1b)+spin(p3b)) THEN
IF (ieor(sym(h4b),ieor(sym(h5b),ieor(sym(h1b),sym(p3b)))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(h4b) * range(h5b) * range(h1b) * range(p3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p6b = noab+1,noab+nvab
IF (spin(p6b) == spin(h1b)) THEN
IF (ieor(sym(p6b),sym(h1b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p6b,h1b,p6b_1,h1b_1)
CALL TCE_RESTRICTED_4(h4b,h5b,p3b,p6b,h4b_2,h5b_2,p3b_2,p6b_2)
dim_common = range(p6b)
dima_sort = range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(h4b) * range(h5b) * range(p3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (p6b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p6b),range(h1b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((p6b < p3b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p3b_2 - 1 + (noab+nvab) * (p6b_2 - 1 + (noab+nvab) * (h5b_2 - 1 + (noab+nvab) * (h4b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h4b),range(h5b),range(p6b),range(p3b),4,2,1,3,-1.0d0)
END IF
IF ((p3b <= p6b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p6b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (h5b_2 - 1 + (noab+nvab) * (h4b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h4b),range(h5b),range(p3b),range(p6b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_4(c_sort,c,range(p3b),range(h5b),range(h4b),range(h1b),3,2,4,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(p3b - noab - 1 + nvab * (h1b - 1 + noab * (h5b - 1 + noab * (h4b - 1)))))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_7(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p2 h1 )_vt + = -1/2 * Sum ( h5 p3 p4 ) * t ( p3 p4 h1 h5 )_t * v ( h5 p2 p3 p4 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h5b
INTEGER :: p3b_1
INTEGER :: p4b_1
INTEGER :: h1b_1
INTEGER :: h5b_1
INTEGER :: p2b_2
INTEGER :: h5b_2
INTEGER :: p3b_2
INTEGER :: p4b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsuperp(2)
INTEGER :: isuperp
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(h1b) /= 4)) THEN
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p2b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p3b = noab+1,noab+nvab
DO p4b = p3b,noab+nvab
DO h5b = 1,noab
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h5b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h5b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p3b,p4b,h1b,h5b,p3b_1,p4b_1,h1b_1,h5b_1)
CALL TCE_RESTRICTED_4(p2b,h5b,p3b,p4b,p2b_2,h5b_2,p3b_2,p4b_2)
dim_common = range(p3b) * range(p4b) * range(h5b)
dima_sort = range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(p2b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((h5b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h5b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p4b),range(h5b),range(h1b),4,3,2,1,-1.0d0)
END IF
IF ((h1b <= h5b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h5b_1 - 1 + noab * (h1b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p4b),range(h1b),range(h5b),3,4,2,1,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h5b <= p2b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p4b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (p2b_2 - 1 + (noab+nvab) * (h5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h5b),range(p2b),range(p3b),range(p4b),2,1,4,3,1.0d0)
END IF
DEALLOCATE(b)
nsuperp(1) = 1
nsuperp(2) = 1
isuperp = 1
IF (p3b == p4b) THEN
nsuperp(isuperp) = nsuperp(isuperp) + 1
ELSE
isuperp = isuperp + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,2.0d0/FACTORIAL(nsuperp(1))/FACTORIAL(nsuperp(2)),a_sort,dim_common,b_sort,dim_co&
&mmon,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(p2b),range(h1b),1,2,-1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE ccsdt_t1_8(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p2 h1 )_vt + = 1/4 * Sum ( h5 h6 p3 p4 ) * t ( p2 p3 p4 h1 h5 h6 )_t * v ( h5 h6 p3 p4 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: dimc
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h5b
INTEGER :: h6b
INTEGER :: p2b_1
INTEGER :: p3b_1
INTEGER :: p4b_1
INTEGER :: h1b_1
INTEGER :: h5b_1
INTEGER :: h6b_1
INTEGER :: h5b_2
INTEGER :: h6b_2
INTEGER :: p3b_2
INTEGER :: p4b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsuperp(2)
INTEGER :: isuperp
INTEGER :: nsubh(2)
INTEGER :: isubh
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p2b)+spin(h1b) /= 4)) THEN
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p2b) * range(h1b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p3b = noab+1,noab+nvab
DO p4b = p3b,noab+nvab
DO h5b = 1,noab
DO h6b = h5b,noab
IF (int_mb(k_active+p2b-1)+int_mb(k_active+p3b-1)+int_mb(k_active+p4b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h5b-1)+int_mb(k_active+h6b-1) .ge. numact) THEN
IF (spin(p2b)+spin(p3b)+spin(p4b) == spin(h1b)+spin(h5b)+spin(h6b)) THEN
IF (ieor(sym(p2b),ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),ieor(sym(h5b),sym(h6b)))))) == irrep_t) THEN
CALL TCE_RESTRICTED_6(p2b,p3b,p4b,h1b,h5b,h6b,p2b_1,p3b_1,p4b_1,h1b_1,h5b_1,h6b_1)
CALL TCE_RESTRICTED_4(h5b,h6b,p3b,p4b,h5b_2,h6b_2,p3b_2,p4b_2)
dim_common = range(p3b) * range(p4b) * range(h5b) * range(h6b)
dima_sort = range(p2b) * range(h1b)
dima = dim_common * dima_sort
dimb_sort = 1
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p4b < p2b) .and. (h6b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h6b_1 - 1 + noab * (h5b_1 - 1 + noab * (p2b_1 - noab - 1 + nvab * (p4b&
&_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p3b),range(p4b),range(p2b),range(h5b),range(h6b),range(h1b),6,3,5,4,2,1,1.0d0)
END IF
IF ((p4b < p2b) .and. (h5b < h1b) .and. (h1b <= h6b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h1b_1 - 1 + noab * (h5b_1 - 1 + noab * (p2b_1 - noab - 1 + nvab * (p4b&
&_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p3b),range(p4b),range(p2b),range(h5b),range(h1b),range(h6b),5,3,6,4,2,1,-1.0d0)
END IF
IF ((p4b < p2b) .and. (h1b <= h5b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h5b_1 - 1 + noab * (h1b_1 - 1 + noab * (p2b_1 - noab - 1 + nvab * (p4b&
&_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p3b),range(p4b),range(p2b),range(h1b),range(h5b),range(h6b),4,3,6,5,2,1,1.0d0)
END IF
IF ((p3b < p2b) .and. (p2b <= p4b) .and. (h6b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h6b_1 - 1 + noab * (h5b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p2b&
&_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p3b),range(p2b),range(p4b),range(h5b),range(h6b),range(h1b),6,2,5,4,3,1,-1.0d0)
END IF
IF ((p3b < p2b) .and. (p2b <= p4b) .and. (h5b < h1b) .and. (h1b <= h6b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h1b_1 - 1 + noab * (h5b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p2b&
&_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p3b),range(p2b),range(p4b),range(h5b),range(h1b),range(h6b),5,2,6,4,3,1,1.0d0)
END IF
IF ((p3b < p2b) .and. (p2b <= p4b) .and. (h1b <= h5b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h5b_1 - 1 + noab * (h1b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p2b&
&_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p3b),range(p2b),range(p4b),range(h1b),range(h5b),range(h6b),4,2,6,5,3,1,-1.0d0)
END IF
IF ((p2b <= p3b) .and. (h6b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h6b_1 - 1 + noab * (h5b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b&
&_1 - noab - 1 + nvab * (p2b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p2b),range(p3b),range(p4b),range(h5b),range(h6b),range(h1b),6,1,5,4,3,2,1.0d0)
END IF
IF ((p2b <= p3b) .and. (h5b < h1b) .and. (h1b <= h6b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h1b_1 - 1 + noab * (h5b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b&
&_1 - noab - 1 + nvab * (p2b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p2b),range(p3b),range(p4b),range(h5b),range(h1b),range(h6b),5,1,6,4,3,2,-1.0d0)
END IF
IF ((p2b <= p3b) .and. (h1b <= h5b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h5b_1 - 1 + noab * (h1b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b&
&_1 - noab - 1 + nvab * (p2b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p2b),range(p3b),range(p4b),range(h1b),range(h5b),range(h6b),4,1,6,5,3,2,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p4b_2 - 1 + (noab+nvab) * (p3b_2 - 1 + (noab+nvab) * (h6b_2 - 1 + (noab+nvab) * (h5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h5b),range(h6b),range(p3b),range(p4b),2,1,4,3,1.0d0)
DEALLOCATE(b)
nsuperp(1) = 1
nsuperp(2) = 1
isuperp = 1
IF (p3b == p4b) THEN
nsuperp(isuperp) = nsuperp(isuperp) + 1
ELSE
isuperp = isuperp + 1
END IF
nsubh(1) = 1
nsubh(2) = 1
isubh = 1
IF (h5b == h6b) THEN
nsubh(isubh) = nsubh(isubh) + 1
ELSE
isubh = isubh + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,4.0d0/FACTORIAL(nsuperp(1))/FACTORIAL(nsuperp(2))/FACTORIAL(nsubh(1))/FACTORIAL(n&
&subh(2)),a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
END IF
END DO
END DO
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_2(c_sort,c,range(h1b),range(p2b),2,1,1.0d0/4.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (p2b - noab - 1)))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
