SUBROUTINE cisdt_c3(d_e0,d_f1,d_i0,d_t1,d_t2,d_t3,d_v2,e0_offset,f1_offset,i0_offset,t1_offset,t2_offset,t3_offset,v2_offset)
!$Id$
!This is a Fortran90 program generated by Tensor Contraction Engine v.1.0
!
!
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = 1 * P( 9 ) * t ( p4 h1 )_t * v ( p5 p6 h2 h3 )_v
!i0 ( p4 p5 p6 h1 h2 h3 )_tf + = 1 * P( 9 ) * t ( p4 p5 h1 h2 )_t * f ( p6 h3 )_f
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = -1 * P( 9 ) * Sum ( h7 ) * t ( p4 p5 h1 h7 )_t * v ( h7 p6 h2 h3 )_v
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = -1 * P( 9 ) * Sum ( p7 ) * t ( p4 p7 h1 h2 )_t * v ( p5 p6 h3 p7 )_v
!i0 ( p4 p5 p6 h1 h2 h3 )_tf + = -1 * P( 3 ) * Sum ( h7 ) * t ( p4 p5 p6 h1 h2 h7 )_t * f ( h7 h3 )_f
!i0 ( p4 p5 p6 h1 h2 h3 )_tf + = 1 * P( 3 ) * Sum ( p7 ) * t ( p4 p5 p7 h1 h2 h3 )_t * f ( p6 p7 )_f
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = 1/2 * P( 3 ) * Sum ( h7 h8 ) * t ( p4 p5 p6 h1 h7 h8 )_t * v ( h7 h8 h2 h3 )_v
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = -1 * P( 9 ) * Sum ( h8 p7 ) * t ( p4 p5 p7 h1 h2 h8 )_t * v ( h8 p6 h3 p7 )_v
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = 1/2 * P( 3 ) * Sum ( p7 p8 ) * t ( p4 p7 p8 h1 h2 h3 )_t * v ( p5 p6 p7 p8 )_v
!i0 ( p4 p5 p6 h1 h2 h3 )_te + = -1 * e ( )_e * t ( p4 p5 p6 h1 h2 h3 )_t
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_i0
INTEGER :: d_t1
INTEGER :: d_v2
INTEGER :: d_t2
INTEGER :: d_f1
INTEGER :: d_t3
INTEGER :: d_e0
INTEGER :: i0_offset(*)
INTEGER :: t1_offset(*)
INTEGER :: v2_offset(*)
INTEGER :: t2_offset(*)
INTEGER :: f1_offset(*)
INTEGER :: t3_offset(*)
INTEGER :: e0_offset(*)
CALL cisdt_c3_1(d_t1,t1_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL cisdt_c3_2(d_t2,t2_offset,d_f1,f1_offset,d_i0,i0_offset)
CALL cisdt_c3_3(d_t2,t2_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL cisdt_c3_4(d_t2,t2_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL cisdt_c3_5(d_t3,t3_offset,d_f1,f1_offset,d_i0,i0_offset)
CALL cisdt_c3_6(d_t3,t3_offset,d_f1,f1_offset,d_i0,i0_offset)
CALL cisdt_c3_7(d_t3,t3_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL cisdt_c3_8(d_t3,t3_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL cisdt_c3_9(d_t3,t3_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL cisdt_c3_10(d_e0,e0_offset,d_t3,t3_offset,d_i0,i0_offset)
RETURN
END
SUBROUTINE cisdt_c3_1(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = 1 * P( 9 ) * t ( p4 h1 )_t * v ( p5 p6 h2 h3 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: p4b_1
INTEGER :: h1b_1
INTEGER :: p5b_2
INTEGER :: p6b_2
INTEGER :: h2b_2
INTEGER :: h3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = noab+1,noab+nvab
DO p6b = p5b,noab+nvab
DO h1b = 1,noab
DO h2b = 1,noab
DO h3b = h2b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
IF (spin(p4b) == spin(h1b)) THEN
IF (ieor(sym(p4b),sym(h1b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p4b,h1b,p4b_1,h1b_1)
CALL TCE_RESTRICTED_4(p5b,p6b,h2b,h3b,p5b_2,p6b_2,h2b_2,h3b_2)
dim_common = 1
dima_sort = range(p4b) * range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(p5b) * range(p6b) * range(h2b) * range(h3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (p4b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p4b),range(h1b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h3b_2 - 1 + (noab+nvab) * (h2b_2 - 1 + (noab+nvab) * (p6b_2 - 1 + (noab+nvab) * (p5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(p5b),range(p6b),range(h2b),range(h3b),4,3,2,1,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
ALLOCATE(c(dimc))
IF ((p4b <= p5b) .and. (h1b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),6,4,3,5,2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p5b) .and. (h2b <= h1b) .and. (h1b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),6,4,3,2,5,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h1b - 1 + noab * (h2b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p5b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),6,4,3,2,1,5,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h3b - 1 + noab * (h2b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p4b) .and. (p4b <= p6b) .and. (h1b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),4,6,3,5,2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p5b <= p4b) .and. (p4b <= p6b) .and. (h2b <= h1b) .and. (h1b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),4,6,3,2,5,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h1b - 1 + noab * (h2b - 1 + noab * (p6b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p5b <= p4b) .and. (p4b <= p6b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),4,6,3,2,1,5,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h3b - 1 + noab * (h2b - 1 + noab * (p6b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h1b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),4,3,6,5,2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h2b <= h1b) .and. (h1b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),4,3,6,2,5,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h1b - 1 + noab * (h2b - 1 + noab * (p4b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(p5b),range(h1b),range(p4b),4,3,6,2,1,5,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h3b - 1 + noab * (h2b - 1 + noab * (p4b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_tf + = 1 * P( 9 ) * t ( p4 p5 h1 h2 )_t * f ( p6 h3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: p4b_1
INTEGER :: p5b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: p6b_2
INTEGER :: h3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = p4b,noab+nvab
DO p6b = noab+1,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
DO h3b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_t,irrep_f)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
IF (spin(p4b)+spin(p5b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(h1b),sym(h2b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p4b,p5b,h1b,h2b,p4b_1,p5b_1,h1b_1,h2b_1)
CALL TCE_RESTRICTED_2(p6b,h3b,p6b_2,h3b_2)
dim_common = 1
dima_sort = range(p4b) * range(p5b) * range(h1b) * range(h2b)
dima = dim_common * dima_sort
dimb_sort = range(p6b) * range(h3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p4b),range(p5b),range(h1b),range(h2b),4,3,2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h3b_2 - 1 + (noab+nvab) * (p6b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(p6b),range(h3b),2,1,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
ALLOCATE(c(dimc))
IF ((p5b <= p6b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,5,2,4,3,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p6b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,5,2,1,4,3,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p6b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,5,2,4,1,3,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),2,6,5,4,3,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),2,6,5,1,4,3,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),2,6,5,4,1,3,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,2,5,4,3,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,2,5,1,4,3,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,2,5,4,1,3,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_3(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = -1 * P( 9 ) * Sum ( h7 ) * t ( p4 p5 h1 h7 )_t * v ( h7 p6 h2 h3 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: h7b
INTEGER :: p4b_1
INTEGER :: p5b_1
INTEGER :: h1b_1
INTEGER :: h7b_1
INTEGER :: p6b_2
INTEGER :: h7b_2
INTEGER :: h2b_2
INTEGER :: h3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = p4b,noab+nvab
DO p6b = noab+1,noab+nvab
DO h1b = 1,noab
DO h2b = 1,noab
DO h3b = h2b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO h7b = 1,noab
IF (spin(p4b)+spin(p5b) == spin(h1b)+spin(h7b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(h1b),sym(h7b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p4b,p5b,h1b,h7b,p4b_1,p5b_1,h1b_1,h7b_1)
CALL TCE_RESTRICTED_4(p6b,h7b,h2b,h3b,p6b_2,h7b_2,h2b_2,h3b_2)
dim_common = range(h7b)
dima_sort = range(p4b) * range(p5b) * range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(p6b) * range(h2b) * range(h3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((h7b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h7b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p4b),range(p5b),range(h7b),range(h1b),4,2,1,3,-1.0d0)
END IF
IF ((h1b <= h7b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h7b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p4b),range(p5b),range(h1b),range(h7b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h7b <= p6b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h3b_2 - 1 + (noab+nvab) * (h2b_2 - 1 + (noab+nvab) * (p6b_2 - 1 + (noab+nvab) * (h7b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h7b),range(p6b),range(h2b),range(h3b),4,3,2,1,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
IF ((p5b <= p6b) .and. (h1b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),6,5,3,4,2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p6b) .and. (h2b <= h1b) .and. (h1b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),6,5,3,2,4,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h1b - 1 + noab * (h2b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p6b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),6,5,3,2,1,4,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h3b - 1 + noab * (h2b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h1b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),3,6,5,4,2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h2b <= h1b) .and. (h1b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),3,6,5,2,4,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h1b - 1 + noab * (h2b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),3,6,5,2,1,4,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h3b - 1 + noab * (h2b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h1b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),6,3,5,4,2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h2b <= h1b) .and. (h1b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),6,3,5,2,4,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h1b - 1 + noab * (h2b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(p6b),range(h1b),range(p5b),range(p4b),6,3,5,2,1,4,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h3b - 1 + noab * (h2b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_4(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = -1 * P( 9 ) * Sum ( p7 ) * t ( p4 p7 h1 h2 )_t * v ( p5 p6 h3 p7 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: p7b
INTEGER :: p4b_1
INTEGER :: p7b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: p5b_2
INTEGER :: p6b_2
INTEGER :: h3b_2
INTEGER :: p7b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = noab+1,noab+nvab
DO p6b = p5b,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
DO h3b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p7b = noab+1,noab+nvab
IF (spin(p4b)+spin(p7b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p4b),ieor(sym(p7b),ieor(sym(h1b),sym(h2b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p4b,p7b,h1b,h2b,p4b_1,p7b_1,h1b_1,h2b_1)
CALL TCE_RESTRICTED_4(p5b,p6b,h3b,p7b,p5b_2,p6b_2,h3b_2,p7b_2)
dim_common = range(p7b)
dima_sort = range(p4b) * range(h1b) * range(h2b)
dima = dim_common * dima_sort
dimb_sort = range(p5b) * range(p6b) * range(h3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p7b < p4b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p7b),range(p4b),range(h1b),range(h2b),4,3,2,1,-1.0d0)
END IF
IF ((p4b <= p7b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p7b_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p4b),range(p7b),range(h1b),range(h2b),4,3,1,2,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h3b <= p7b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p7b_2 - 1 + (noab+nvab) * (h3b_2 - 1 + (noab+nvab) * (p6b_2 - 1 + (noab+nvab) * (p5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(p5b),range(p6b),range(h3b),range(p7b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
IF ((p4b <= p5b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),6,3,2,5,4,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p5b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),6,3,2,1,5,4,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p5b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),6,3,2,5,1,4,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p4b) .and. (p4b <= p6b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),3,6,2,5,4,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p5b <= p4b) .and. (p4b <= p6b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),3,6,2,1,5,4,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p6b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p5b <= p4b) .and. (p4b <= p6b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),3,6,2,5,1,4,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),3,2,6,5,4,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),3,2,6,1,5,4,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p4b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(p5b),range(h2b),range(h1b),range(p4b),3,2,6,5,1,4,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_5(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_tf + = -1 * P( 3 ) * Sum ( h7 ) * t ( p4 p5 p6 h1 h2 h7 )_t * f ( h7 h3 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: h7b
INTEGER :: p4b_1
INTEGER :: p5b_1
INTEGER :: p6b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: h7b_1
INTEGER :: h7b_2
INTEGER :: h3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = p4b,noab+nvab
DO p6b = p5b,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
DO h3b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_t,irrep_f)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO h7b = 1,noab
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h7b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h7b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h7b)))))) == irrep_t) THEN
CALL TCE_RESTRICTED_6(p4b,p5b,p6b,h1b,h2b,h7b,p4b_1,p5b_1,p6b_1,h1b_1,h2b_1,h7b_1)
CALL TCE_RESTRICTED_2(h7b,h3b,h7b_2,h3b_2)
dim_common = range(h7b)
dima_sort = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b)
dima = dim_common * dima_sort
dimb_sort = range(h3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((h7b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (h7b_1 - 1 + noab * (p6b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p6b),range(h7b),range(h1b),range(h2b),6,5,3,2,1,4,1.0d0)
END IF
IF ((h1b <= h7b) .and. (h7b < h2b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h7b_1 - 1 + noab * (h1b_1 - 1 + noab * (p6b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p6b),range(h1b),range(h7b),range(h2b),6,4,3,2,1,5,-1.0d0)
END IF
IF ((h2b <= h7b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h7b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p6b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p6b),range(h1b),range(h2b),range(h7b),5,4,3,2,1,6,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h3b_2 - 1 + (noab+nvab) * (h7b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(h7b),range(h3b),2,1,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
IF ((h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(h1b),range(p6b),range(p5b),range(p4b),6,5,4,3,2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(h1b),range(p6b),range(p5b),range(p4b),6,5,4,1,3,2,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(h1b),range(p6b),range(p5b),range(p4b),6,5,4,3,1,2,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_6(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_tf + = 1 * P( 3 ) * Sum ( p7 ) * t ( p4 p5 p7 h1 h2 h3 )_t * f ( p6 p7 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: p7b
INTEGER :: p4b_1
INTEGER :: p5b_1
INTEGER :: p7b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: h3b_1
INTEGER :: p6b_2
INTEGER :: p7b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = p4b,noab+nvab
DO p6b = noab+1,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
DO h3b = h2b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_t,irrep_f)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p7b = noab+1,noab+nvab
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p7b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p7b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p7b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == irrep_t) THEN
CALL TCE_RESTRICTED_6(p4b,p5b,p7b,h1b,h2b,h3b,p4b_1,p5b_1,p7b_1,h1b_1,h2b_1,h3b_1)
CALL TCE_RESTRICTED_2(p6b,p7b,p6b_2,p7b_2)
dim_common = range(p7b)
dima_sort = range(p4b) * range(p5b) * range(h1b) * range(h2b) * range(h3b)
dima = dim_common * dima_sort
dimb_sort = range(p6b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p7b < p4b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h3b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p4b&
&_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p7b),range(p4b),range(p5b),range(h1b),range(h2b),range(h3b),6,5,4,3,2,1,1.0d0)
END IF
IF ((p4b <= p7b) .and. (p7b < p5b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h3b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p7b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p7b),range(p5b),range(h1b),range(h2b),range(h3b),6,5,4,3,1,2,-1.0d0)
END IF
IF ((p5b <= p7b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h3b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p7b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p7b),range(h1b),range(h2b),range(h3b),6,5,4,2,1,3,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p7b_2 - 1 + (noab+nvab) * (p6b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(p6b),range(p7b),1,2,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
IF ((p5b <= p6b)) THEN
CALL TCE_SORT_6(c_sort,c,range(p6b),range(h3b),range(h2b),range(h1b),range(p5b),range(p4b),6,5,1,4,3,2,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p6b <= p4b)) THEN
CALL TCE_SORT_6(c_sort,c,range(p6b),range(h3b),range(h2b),range(h1b),range(p5b),range(p4b),1,6,5,4,3,2,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b)) THEN
CALL TCE_SORT_6(c_sort,c,range(p6b),range(h3b),range(h2b),range(h1b),range(p5b),range(p4b),6,1,5,4,3,2,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_7(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = 1/2 * P( 3 ) * Sum ( h7 h8 ) * t ( p4 p5 p6 h1 h7 h8 )_t * v ( h7 h8 h2 h3 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: h7b
INTEGER :: h8b
INTEGER :: p4b_1
INTEGER :: p5b_1
INTEGER :: p6b_1
INTEGER :: h1b_1
INTEGER :: h7b_1
INTEGER :: h8b_1
INTEGER :: h7b_2
INTEGER :: h8b_2
INTEGER :: h2b_2
INTEGER :: h3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsubh(2)
INTEGER :: isubh
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = p4b,noab+nvab
DO p6b = p5b,noab+nvab
DO h1b = 1,noab
DO h2b = 1,noab
DO h3b = h2b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO h7b = 1,noab
DO h8b = h7b,noab
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h7b-1)+int_mb(k_active+h8b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h7b)+spin(h8b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h7b),sym(h8b)))))) == irrep_t) THEN
CALL TCE_RESTRICTED_6(p4b,p5b,p6b,h1b,h7b,h8b,p4b_1,p5b_1,p6b_1,h1b_1,h7b_1,h8b_1)
CALL TCE_RESTRICTED_4(h7b,h8b,h2b,h3b,h7b_2,h8b_2,h2b_2,h3b_2)
dim_common = range(h7b) * range(h8b)
dima_sort = range(p4b) * range(p5b) * range(p6b) * range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(h2b) * range(h3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((h8b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h8b_1 - 1 + noab * (h7b_1 - 1 + noab * (p6b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p6b),range(h7b),range(h8b),range(h1b),6,3,2,1,5,4,1.0d0)
END IF
IF ((h7b < h1b) .and. (h1b <= h8b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h8b_1 - 1 + noab * (h1b_1 - 1 + noab * (h7b_1 - 1 + noab * (p6b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p6b),range(h7b),range(h1b),range(h8b),5,3,2,1,6,4,-1.0d0)
END IF
IF ((h1b <= h7b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h8b_1 - 1 + noab * (h7b_1 - 1 + noab * (h1b_1 - 1 + noab * (p6b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p6b),range(h1b),range(h7b),range(h8b),4,3,2,1,6,5,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h3b_2 - 1 + (noab+nvab) * (h2b_2 - 1 + (noab+nvab) * (h8b_2 - 1 + (noab+nvab) * (h7b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h7b),range(h8b),range(h2b),range(h3b),4,3,2,1,1.0d0)
DEALLOCATE(b)
nsubh(1) = 1
nsubh(2) = 1
isubh = 1
IF (h7b == h8b) THEN
nsubh(isubh) = nsubh(isubh) + 1
ELSE
isubh = isubh + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,2.0d0/FACTORIAL(nsubh(1))/FACTORIAL(nsubh(2)),a_sort,dim_common,b_sort,dim_common&
&,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
IF ((h1b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(h1b),range(p6b),range(p5b),range(p4b),6,5,4,3,2,1,1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((h2b <= h1b) .and. (h1b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(h1b),range(p6b),range(p5b),range(p4b),6,5,4,2,3,1,-1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h1b - 1 + noab * (h2b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(h1b),range(p6b),range(p5b),range(p4b),6,5,4,2,1,3,1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h3b - 1 + noab * (h2b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_8(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = -1 * P( 9 ) * Sum ( h8 p7 ) * t ( p4 p5 p7 h1 h2 h8 )_t * v ( h8 p6 h3 p7 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: p7b
INTEGER :: h8b
INTEGER :: p4b_1
INTEGER :: p5b_1
INTEGER :: p7b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: h8b_1
INTEGER :: p6b_2
INTEGER :: h8b_2
INTEGER :: h3b_2
INTEGER :: p7b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = p4b,noab+nvab
DO p6b = noab+1,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
DO h3b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p7b = noab+1,noab+nvab
DO h8b = 1,noab
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p7b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h8b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p7b) == spin(h1b)+spin(h2b)+spin(h8b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p7b),ieor(sym(h1b),ieor(sym(h2b),sym(h8b)))))) == irrep_t) THEN
CALL TCE_RESTRICTED_6(p4b,p5b,p7b,h1b,h2b,h8b,p4b_1,p5b_1,p7b_1,h1b_1,h2b_1,h8b_1)
CALL TCE_RESTRICTED_4(p6b,h8b,h3b,p7b,p6b_2,h8b_2,h3b_2,p7b_2)
dim_common = range(p7b) * range(h8b)
dima_sort = range(p4b) * range(p5b) * range(h1b) * range(h2b)
dima = dim_common * dima_sort
dimb_sort = range(p6b) * range(h3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p7b < p4b) .and. (h8b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (h8b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p4b&
&_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p7b),range(p4b),range(p5b),range(h8b),range(h1b),range(h2b),6,5,3,2,4,1,1.0d0)
END IF
IF ((p7b < p4b) .and. (h1b <= h8b) .and. (h8b < h2b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h8b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p4b&
&_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p7b),range(p4b),range(p5b),range(h1b),range(h8b),range(h2b),6,4,3,2,5,1,-1.0d0)
END IF
IF ((p7b < p4b) .and. (h2b <= h8b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h8b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p4b&
&_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p7b),range(p4b),range(p5b),range(h1b),range(h2b),range(h8b),5,4,3,2,6,1,1.0d0)
END IF
IF ((p4b <= p7b) .and. (p7b < p5b) .and. (h8b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (h8b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p7b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p7b),range(p5b),range(h8b),range(h1b),range(h2b),6,5,3,1,4,2,-1.0d0)
END IF
IF ((p4b <= p7b) .and. (p7b < p5b) .and. (h1b <= h8b) .and. (h8b < h2b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h8b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p7b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p7b),range(p5b),range(h1b),range(h8b),range(h2b),6,4,3,1,5,2,1.0d0)
END IF
IF ((p4b <= p7b) .and. (p7b < p5b) .and. (h2b <= h8b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h8b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p7b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p7b),range(p5b),range(h1b),range(h2b),range(h8b),5,4,3,1,6,2,-1.0d0)
END IF
IF ((p5b <= p7b) .and. (h8b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (h8b_1 - 1 + noab * (p7b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p7b),range(h8b),range(h1b),range(h2b),6,5,2,1,4,3,1.0d0)
END IF
IF ((p5b <= p7b) .and. (h1b <= h8b) .and. (h8b < h2b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h8b_1 - 1 + noab * (h1b_1 - 1 + noab * (p7b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p7b),range(h1b),range(h8b),range(h2b),6,4,2,1,5,3,-1.0d0)
END IF
IF ((p5b <= p7b) .and. (h2b <= h8b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h8b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p7b_1 - noab - 1 + nvab * (p5b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p5b),range(p7b),range(h1b),range(h2b),range(h8b),5,4,2,1,6,3,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h8b <= p6b) .and. (h3b <= p7b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p7b_2 - 1 + (noab+nvab) * (h3b_2 - 1 + (noab+nvab) * (p6b_2 - 1 + (noab+nvab) * (h8b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h8b),range(p6b),range(h3b),range(p7b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
IF ((p5b <= p6b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,5,2,4,3,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p6b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,5,2,1,4,3,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p6b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,5,2,4,1,3,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),2,6,5,4,3,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),2,6,5,1,4,3,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p6b <= p4b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),2,6,5,4,1,3,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p6b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h2b <= h3b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,2,5,4,3,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h3b <= h1b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,2,5,1,4,3,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (h3b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p4b <= p6b) .and. (p6b <= p5b) .and. (h1b <= h3b) .and. (h3b <= h2b)) THEN
CALL TCE_SORT_6(c_sort,c,range(h3b),range(p6b),range(h2b),range(h1b),range(p5b),range(p4b),6,2,5,4,1,3,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h3b - 1 + noab * (h1b - 1 + noab * (p5b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_9(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_vt + = 1/2 * P( 3 ) * Sum ( p7 p8 ) * t ( p4 p7 p8 h1 h2 h3 )_t * v ( p5 p6 p7 p8 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: p7b
INTEGER :: p8b
INTEGER :: p4b_1
INTEGER :: p7b_1
INTEGER :: p8b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: h3b_1
INTEGER :: p5b_2
INTEGER :: p6b_2
INTEGER :: p7b_2
INTEGER :: p8b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsuperp(2)
INTEGER :: isuperp
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = noab+1,noab+nvab
DO p6b = p5b,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
DO h3b = h2b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p7b = noab+1,noab+nvab
DO p8b = p7b,noab+nvab
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p7b-1)+int_mb(k_active+p8b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p7b)+spin(p8b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p7b),ieor(sym(p8b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == irrep_t) THEN
CALL TCE_RESTRICTED_6(p4b,p7b,p8b,h1b,h2b,h3b,p4b_1,p7b_1,p8b_1,h1b_1,h2b_1,h3b_1)
CALL TCE_RESTRICTED_4(p5b,p6b,p7b,p8b,p5b_2,p6b_2,p7b_2,p8b_2)
dim_common = range(p7b) * range(p8b)
dima_sort = range(p4b) * range(h1b) * range(h2b) * range(h3b)
dima = dim_common * dima_sort
dimb_sort = range(p5b) * range(p6b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p8b < p4b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h3b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p8b&
&_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p7b),range(p8b),range(p4b),range(h1b),range(h2b),range(h3b),6,5,4,3,2,1,1.0d0)
END IF
IF ((p7b < p4b) .and. (p4b <= p8b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h3b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p8b_1 - noab - 1 + nvab * (p4b&
&_1 - noab - 1 + nvab * (p7b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p7b),range(p4b),range(p8b),range(h1b),range(h2b),range(h3b),6,5,4,2,3,1,-1.0d0)
END IF
IF ((p4b <= p7b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h3b_1 - 1 + noab * (h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p8b_1 - noab - 1 + nvab * (p7b&
&_1 - noab - 1 + nvab * (p4b_1 - noab - 1)))))))
CALL TCE_SORT_6(a,a_sort,range(p4b),range(p7b),range(p8b),range(h1b),range(h2b),range(h3b),6,5,4,1,3,2,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p8b_2 - 1 + (noab+nvab) * (p7b_2 - 1 + (noab+nvab) * (p6b_2 - 1 + (noab+nvab) * (p5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(p5b),range(p6b),range(p7b),range(p8b),2,1,4,3,1.0d0)
DEALLOCATE(b)
nsuperp(1) = 1
nsuperp(2) = 1
isuperp = 1
IF (p7b == p8b) THEN
nsuperp(isuperp) = nsuperp(isuperp) + 1
ELSE
isuperp = isuperp + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,2.0d0/FACTORIAL(nsuperp(1))/FACTORIAL(nsuperp(2)),a_sort,dim_common,b_sort,dim_co&
&mmon,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
IF ((p4b <= p5b)) THEN
CALL TCE_SORT_6(c_sort,c,range(p6b),range(p5b),range(h3b),range(h2b),range(h1b),range(p4b),6,2,1,5,4,3,1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
END IF
IF ((p5b <= p4b) .and. (p4b <= p6b)) THEN
CALL TCE_SORT_6(c_sort,c,range(p6b),range(p5b),range(h3b),range(h2b),range(h1b),range(p4b),2,6,1,5,4,3,-1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p4b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
IF ((p6b <= p4b)) THEN
CALL TCE_SORT_6(c_sort,c,range(p6b),range(p5b),range(h3b),range(h2b),range(h1b),range(p4b),2,1,6,5,4,3,1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p6b - noab &
&- 1 + nvab * (p5b - noab - 1)))))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE cisdt_c3_10(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p4 p5 p6 h1 h2 h3 )_te + = -1 * e ( )_e * t ( p4 p5 p6 h1 h2 h3 )_t
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p4b
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: h3b
INTEGER :: dimc
INTEGER :: p4b_2
INTEGER :: p5b_2
INTEGER :: p6b_2
INTEGER :: h1b_2
INTEGER :: h2b_2
INTEGER :: h3b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p4b = noab+1,noab+nvab
DO p5b = p4b,noab+nvab
DO p6b = p5b,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
DO h3b = h2b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p4b)+spin(p5b)+spin(p6b)+spin(h1b)+spin(h2b)+spin(h3b) /= 12)) THEN
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (spin(p4b)+spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)+spin(h3b)) THEN
IF (ieor(sym(p4b),ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),ieor(sym(h2b),sym(h3b)))))) == ieor(irrep_t,irrep_e)) THEN
dimc = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
IF (int_mb(k_active+p4b-1)+int_mb(k_active+p5b-1)+int_mb(k_active+p6b-1) .ge. numact) THEN
IF (int_mb(k_active+h1b-1)+int_mb(k_active+h2b-1)+int_mb(k_active+h3b-1) .ge. numact) THEN
IF (0 == irrep_e) THEN
CALL TCE_RESTRICTED_6(p4b,p5b,p6b,h1b,h2b,h3b,p4b_2,p5b_2,p6b_2,h1b_2,h2b_2,h3b_2)
dim_common = 1
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = range(p4b) * range(p5b) * range(p6b) * range(h1b) * range(h2b) * range(h3b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,0)
CALL TCE_SORT_0(a,a_sort,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h3b_2 - 1 + noab * (h2b_2 - 1 + noab * (h1b_2 - 1 + noab * (p6b_2 - noab - 1 + nvab * (p5b&
&_2 - noab - 1 + nvab * (p4b_2 - noab - 1)))))))
CALL TCE_SORT_6(b,b_sort,range(p4b),range(p5b),range(p6b),range(h1b),range(h2b),range(h3b),6,5,4,3,2,1,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
ALLOCATE(c(dimc))
CALL TCE_SORT_6(c_sort,c,range(h3b),range(h2b),range(h1b),range(p6b),range(p5b),range(p4b),6,5,4,3,2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h3b - 1 + noab * (h2b - 1 + noab * (h1b - 1 + noab * (p6b - noab - 1 + nvab * (p5b - noab &
&- 1 + nvab * (p4b - noab - 1)))))))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
