SUBROUTINE lccsd_e(d_f1,d_i0,d_t1,d_t2,d_v2,f1_offset,i0_offset,t1_offset,t2_offset,v2_offset)
!$Id$
!This is a Fortran90 program generated by Tensor Contraction Engine v.1.0
!
!
!i0 ( )_tf + = 1 * Sum ( p2 h1 ) * t ( p2 h1 )_t * f ( h1 p2 )_f
!i0 ( )_vt + = 1/4 * Sum ( h3 h4 p1 p2 ) * t ( p1 p2 h3 h4 )_t * v ( h3 h4 p1 p2 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_i0
INTEGER :: d_t1
INTEGER :: d_f1
INTEGER :: d_t2
INTEGER :: d_v2
INTEGER :: i0_offset(*)
INTEGER :: t1_offset(*)
INTEGER :: f1_offset(*)
INTEGER :: t2_offset(*)
INTEGER :: v2_offset(*)
CALL lccsd_e_1(d_t1,t1_offset,d_f1,f1_offset,d_i0,i0_offset)
CALL lccsd_e_2(d_t2,t2_offset,d_v2,v2_offset,d_i0,i0_offset)
RETURN
END
SUBROUTINE lccsd_e_1(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( )_tf + = 1 * Sum ( p2 h1 ) * t ( p2 h1 )_t * f ( h1 p2 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: dimc
INTEGER :: p2b
INTEGER :: h1b
INTEGER :: p2b_1
INTEGER :: h1b_1
INTEGER :: h1b_2
INTEGER :: p2b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
IF (next == count) THEN
IF (0 == ieor(irrep_t,irrep_f)) THEN
dimc = 1
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p2b = noab+1,noab+nvab
DO h1b = 1,noab
IF (spin(p2b) == spin(h1b)) THEN
IF (ieor(sym(p2b),sym(h1b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p2b,h1b,p2b_1,h1b_1)
CALL TCE_RESTRICTED_2(h1b,p2b,h1b_2,p2b_2)
dim_common = range(p2b) * range(h1b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = 1
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (p2b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p2b),range(h1b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p2b_2 - 1 + (noab+nvab) * (h1b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(h1b),range(p2b),1,2,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_0(c_sort,c,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,0)
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE lccsd_e_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( )_vt + = 1/4 * Sum ( h3 h4 p1 p2 ) * t ( p1 p2 h3 h4 )_t * v ( h3 h4 p1 p2 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: dimc
INTEGER :: p1b
INTEGER :: p2b
INTEGER :: h3b
INTEGER :: h4b
INTEGER :: p1b_1
INTEGER :: p2b_1
INTEGER :: h3b_1
INTEGER :: h4b_1
INTEGER :: h3b_2
INTEGER :: h4b_2
INTEGER :: p1b_2
INTEGER :: p2b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsuperp(2)
INTEGER :: isuperp
INTEGER :: nsubh(2)
INTEGER :: isubh
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
IF (next == count) THEN
IF (0 == ieor(irrep_v,irrep_t)) THEN
dimc = 1
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p1b = noab+1,noab+nvab
DO p2b = p1b,noab+nvab
DO h3b = 1,noab
DO h4b = h3b,noab
IF (spin(p1b)+spin(p2b) == spin(h3b)+spin(h4b)) THEN
IF (ieor(sym(p1b),ieor(sym(p2b),ieor(sym(h3b),sym(h4b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p1b,p2b,h3b,h4b,p1b_1,p2b_1,h3b_1,h4b_1)
CALL TCE_RESTRICTED_4(h3b,h4b,p1b,p2b,h3b_2,h4b_2,p1b_2,p2b_2)
dim_common = range(p1b) * range(p2b) * range(h3b) * range(h4b)
dima_sort = 1
dima = dim_common * dima_sort
dimb_sort = 1
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h4b_1 - 1 + noab * (h3b_1 - 1 + noab * (p2b_1 - noab - 1 + nvab * (p1b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p1b),range(p2b),range(h3b),range(h4b),4,3,2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p2b_2 - 1 + (noab+nvab) * (p1b_2 - 1 + (noab+nvab) * (h4b_2 - 1 + (noab+nvab) * (h3b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h3b),range(h4b),range(p1b),range(p2b),2,1,4,3,1.0d0)
DEALLOCATE(b)
nsuperp(1) = 1
nsuperp(2) = 1
isuperp = 1
IF (p1b == p2b) THEN
nsuperp(isuperp) = nsuperp(isuperp) + 1
ELSE
isuperp = isuperp + 1
END IF
nsubh(1) = 1
nsubh(2) = 1
isubh = 1
IF (h3b == h4b) THEN
nsubh(isubh) = nsubh(isubh) + 1
ELSE
isubh = isubh + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,4.0d0/FACTORIAL(nsuperp(1))/FACTORIAL(nsuperp(2))/FACTORIAL(nsubh(1))/FACTORIAL(n&
&subh(2)),a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_0(c_sort,c,1.0d0/4.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,0)
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
