SUBROUTINE lccsd_t2(d_f1,d_i0,d_t1,d_t2,d_v2,f1_offset,i0_offset,t1_offset,t2_offset,v2_offset)
!$Id$
!This is a Fortran90 program generated by Tensor Contraction Engine v.1.0
!
!
!i0 ( p3 p4 h1 h2 )_v + = 1 * v ( p3 p4 h1 h2 )_v
!i0 ( p3 p4 h1 h2 )_vt + = -1 * P( 2 ) * Sum ( h5 ) * t ( p3 h5 )_t * v ( h5 p4 h1 h2 )_v
!i0 ( p3 p4 h1 h2 )_vt + = -1 * P( 2 ) * Sum ( p5 ) * t ( p5 h1 )_t * v ( p3 p4 h2 p5 )_v
!i0 ( p3 p4 h1 h2 )_tf + = -1 * P( 2 ) * Sum ( h5 ) * t ( p3 p4 h1 h5 )_t * f ( h5 h2 )_f
!i0 ( p3 p4 h1 h2 )_tf + = 1 * P( 2 ) * Sum ( p5 ) * t ( p3 p5 h1 h2 )_t * f ( p4 p5 )_f
!i0 ( p3 p4 h1 h2 )_vt + = 1/2 * Sum ( h5 h6 ) * t ( p3 p4 h5 h6 )_t * v ( h5 h6 h1 h2 )_v
!i0 ( p3 p4 h1 h2 )_vt + = -1 * P( 4 ) * Sum ( h6 p5 ) * t ( p3 p5 h1 h6 )_t * v ( h6 p4 h2 p5 )_v
!i0 ( p3 p4 h1 h2 )_vt + = 1/2 * Sum ( p5 p6 ) * t ( p5 p6 h1 h2 )_t * v ( p3 p4 p5 p6 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_i0
INTEGER :: d_v2
INTEGER :: d_t1
INTEGER :: d_t2
INTEGER :: d_f1
INTEGER :: i0_offset(*)
INTEGER :: v2_offset(*)
INTEGER :: t1_offset(*)
INTEGER :: t2_offset(*)
INTEGER :: f1_offset(*)
CALL lccsd_t2_1(d_v2,v2_offset,d_i0,i0_offset)
CALL lccsd_t2_2(d_t1,t1_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL lccsd_t2_3(d_t1,t1_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL lccsd_t2_4(d_t2,t2_offset,d_f1,f1_offset,d_i0,i0_offset)
CALL lccsd_t2_5(d_t2,t2_offset,d_f1,f1_offset,d_i0,i0_offset)
CALL lccsd_t2_6(d_t2,t2_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL lccsd_t2_7(d_t2,t2_offset,d_v2,v2_offset,d_i0,i0_offset)
CALL lccsd_t2_8(d_t2,t2_offset,d_v2,v2_offset,d_i0,i0_offset)
RETURN
END
SUBROUTINE lccsd_t2_1(d_a,a_offset,d_c,c_offset)
!i0 ( p3 p4 h1 h2 )_v + = 1 * v ( p3 p4 h1 h2 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: dimc
INTEGER :: p3b_1
INTEGER :: p4b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: a_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p3b = noab+1,noab+nvab
DO p4b = p3b,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p3b)+spin(p4b)+spin(h1b)+spin(h2b) /= 8)) THEN
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h2b)))) == irrep_v) THEN
dimc = range(p3b) * range(p4b) * range(h1b) * range(h2b)
CALL TCE_RESTRICTED_4(p3b,p4b,h1b,h2b,p3b_1,p4b_1,h1b_1,h2b_1)
dim_common = 1
dima_sort = range(p3b) * range(p4b) * range(h1b) * range(h2b)
dima = dim_common * dima_sort
IF (dima > 0) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + (noab+nvab) * (h1b_1 - 1 + (noab+nvab) * (p4b_1 - 1 + (noab+nvab) * (p3b_1 - 1&
&)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p4b),range(h1b),range(h2b),4,3,2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(c(dimc))
CALL TCE_SORT_4(a_sort,c,range(h2b),range(h1b),range(p4b),range(p3b),4,3,2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
DEALLOCATE(c)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE lccsd_t2_2(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p3 p4 h1 h2 )_vt + = -1 * P( 2 ) * Sum ( h5 ) * t ( p3 h5 )_t * v ( h5 p4 h1 h2 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: dimc
INTEGER :: h5b
INTEGER :: p3b_1
INTEGER :: h5b_1
INTEGER :: p4b_2
INTEGER :: h5b_2
INTEGER :: h1b_2
INTEGER :: h2b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p3b = noab+1,noab+nvab
DO p4b = noab+1,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p3b)+spin(p4b)+spin(h1b)+spin(h2b) /= 8)) THEN
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h2b)))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p3b) * range(p4b) * range(h1b) * range(h2b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO h5b = 1,noab
IF (spin(p3b) == spin(h5b)) THEN
IF (ieor(sym(p3b),sym(h5b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p3b,h5b,p3b_1,h5b_1)
CALL TCE_RESTRICTED_4(p4b,h5b,h1b,h2b,p4b_2,h5b_2,h1b_2,h2b_2)
dim_common = range(h5b)
dima_sort = range(p3b)
dima = dim_common * dima_sort
dimb_sort = range(p4b) * range(h1b) * range(h2b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h5b_1 - 1 + noab * (p3b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p3b),range(h5b),1,2,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h5b <= p4b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h2b_2 - 1 + (noab+nvab) * (h1b_2 - 1 + (noab+nvab) * (p4b_2 - 1 + (noab+nvab) * (h5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h5b),range(p4b),range(h1b),range(h2b),4,3,2,1,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
IF ((p3b <= p4b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(h1b),range(p4b),range(p3b),4,3,2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
END IF
IF ((p4b <= p3b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(h1b),range(p4b),range(p3b),3,4,2,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p3b - noab - 1 + nvab * (p4b - noab - 1)))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE lccsd_t2_3(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p3 p4 h1 h2 )_vt + = -1 * P( 2 ) * Sum ( p5 ) * t ( p5 h1 )_t * v ( p3 p4 h2 p5 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: dimc
INTEGER :: p5b
INTEGER :: p5b_1
INTEGER :: h1b_1
INTEGER :: p3b_2
INTEGER :: p4b_2
INTEGER :: h2b_2
INTEGER :: p5b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p3b = noab+1,noab+nvab
DO p4b = p3b,noab+nvab
DO h1b = 1,noab
DO h2b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p3b)+spin(p4b)+spin(h1b)+spin(h2b) /= 8)) THEN
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h2b)))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p3b) * range(p4b) * range(h1b) * range(h2b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p5b = noab+1,noab+nvab
IF (spin(p5b) == spin(h1b)) THEN
IF (ieor(sym(p5b),sym(h1b)) == irrep_t) THEN
CALL TCE_RESTRICTED_2(p5b,h1b,p5b_1,h1b_1)
CALL TCE_RESTRICTED_4(p3b,p4b,h2b,p5b,p3b_2,p4b_2,h2b_2,p5b_2)
dim_common = range(p5b)
dima_sort = range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(p3b) * range(p4b) * range(h2b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (p5b_1 - noab - 1)))
CALL TCE_SORT_2(a,a_sort,range(p5b),range(h1b),2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h2b <= p5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (h2b_2 - 1 + (noab+nvab) * (p4b_2 - 1 + (noab+nvab) * (p3b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(p3b),range(p4b),range(h2b),range(p5b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
IF ((h1b <= h2b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(p4b),range(p3b),range(h1b),3,2,4,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
END IF
IF ((h2b <= h1b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(p4b),range(p3b),range(h1b),3,2,1,4,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h2b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE lccsd_t2_4(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p3 p4 h1 h2 )_tf + = -1 * P( 2 ) * Sum ( h5 ) * t ( p3 p4 h1 h5 )_t * f ( h5 h2 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: dimc
INTEGER :: h5b
INTEGER :: p3b_1
INTEGER :: p4b_1
INTEGER :: h1b_1
INTEGER :: h5b_1
INTEGER :: h5b_2
INTEGER :: h2b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p3b = noab+1,noab+nvab
DO p4b = p3b,noab+nvab
DO h1b = 1,noab
DO h2b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p3b)+spin(p4b)+spin(h1b)+spin(h2b) /= 8)) THEN
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h2b)))) == ieor(irrep_t,irrep_f)) THEN
dimc = range(p3b) * range(p4b) * range(h1b) * range(h2b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO h5b = 1,noab
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h5b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h5b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p3b,p4b,h1b,h5b,p3b_1,p4b_1,h1b_1,h5b_1)
CALL TCE_RESTRICTED_2(h5b,h2b,h5b_2,h2b_2)
dim_common = range(h5b)
dima_sort = range(p3b) * range(p4b) * range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(h2b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((h5b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h5b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p4b),range(h5b),range(h1b),4,2,1,3,-1.0d0)
END IF
IF ((h1b <= h5b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h5b_1 - 1 + noab * (h1b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p4b),range(h1b),range(h5b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h2b_2 - 1 + (noab+nvab) * (h5b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(h5b),range(h2b),2,1,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
IF ((h1b <= h2b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(h1b),range(p4b),range(p3b),4,3,2,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
END IF
IF ((h2b <= h1b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(h1b),range(p4b),range(p3b),4,3,1,2,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h2b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE lccsd_t2_5(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p3 p4 h1 h2 )_tf + = 1 * P( 2 ) * Sum ( p5 ) * t ( p3 p5 h1 h2 )_t * f ( p4 p5 )_f
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: dimc
INTEGER :: p5b
INTEGER :: p3b_1
INTEGER :: p5b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: p4b_2
INTEGER :: p5b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p3b = noab+1,noab+nvab
DO p4b = noab+1,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p3b)+spin(p4b)+spin(h1b)+spin(h2b) /= 8)) THEN
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h2b)))) == ieor(irrep_t,irrep_f)) THEN
dimc = range(p3b) * range(p4b) * range(h1b) * range(h2b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p5b = noab+1,noab+nvab
IF (spin(p3b)+spin(p5b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p5b),ieor(sym(h1b),sym(h2b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p3b,p5b,h1b,h2b,p3b_1,p5b_1,h1b_1,h2b_1)
CALL TCE_RESTRICTED_2(p4b,p5b,p4b_2,p5b_2)
dim_common = range(p5b)
dima_sort = range(p3b) * range(h1b) * range(h2b)
dima = dim_common * dima_sort
dimb_sort = range(p4b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p5b < p3b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p3b_1 - noab - 1 + nvab * (p5b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p5b),range(p3b),range(h1b),range(h2b),4,3,2,1,-1.0d0)
END IF
IF ((p3b <= p5b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p5b),range(h1b),range(h2b),4,3,1,2,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (p4b_2 - 1)))
CALL TCE_SORT_2(b,b_sort,range(p4b),range(p5b),1,2,1.0d0)
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
ALLOCATE(c(dimc))
IF ((p3b <= p4b)) THEN
CALL TCE_SORT_4(c_sort,c,range(p4b),range(h2b),range(h1b),range(p3b),4,1,3,2,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
END IF
IF ((p4b <= p3b)) THEN
CALL TCE_SORT_4(c_sort,c,range(p4b),range(h2b),range(h1b),range(p3b),1,4,3,2,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p3b - noab - 1 + nvab * (p4b - noab - 1)))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE lccsd_t2_6(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p3 p4 h1 h2 )_vt + = 1/2 * Sum ( h5 h6 ) * t ( p3 p4 h5 h6 )_t * v ( h5 h6 h1 h2 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: dimc
INTEGER :: h5b
INTEGER :: h6b
INTEGER :: p3b_1
INTEGER :: p4b_1
INTEGER :: h5b_1
INTEGER :: h6b_1
INTEGER :: h5b_2
INTEGER :: h6b_2
INTEGER :: h1b_2
INTEGER :: h2b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsubh(2)
INTEGER :: isubh
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p3b = noab+1,noab+nvab
DO p4b = p3b,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p3b)+spin(p4b)+spin(h1b)+spin(h2b) /= 8)) THEN
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h2b)))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p3b) * range(p4b) * range(h1b) * range(h2b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO h5b = 1,noab
DO h6b = h5b,noab
IF (spin(p3b)+spin(p4b) == spin(h5b)+spin(h6b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h5b),sym(h6b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p3b,p4b,h5b,h6b,p3b_1,p4b_1,h5b_1,h6b_1)
CALL TCE_RESTRICTED_4(h5b,h6b,h1b,h2b,h5b_2,h6b_2,h1b_2,h2b_2)
dim_common = range(h5b) * range(h6b)
dima_sort = range(p3b) * range(p4b)
dima = dim_common * dima_sort
dimb_sort = range(h1b) * range(h2b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h5b_1 - 1 + noab * (p4b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p4b),range(h5b),range(h6b),2,1,4,3,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(h2b_2 - 1 + (noab+nvab) * (h1b_2 - 1 + (noab+nvab) * (h6b_2 - 1 + (noab+nvab) * (h5b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h5b),range(h6b),range(h1b),range(h2b),4,3,2,1,1.0d0)
DEALLOCATE(b)
nsubh(1) = 1
nsubh(2) = 1
isubh = 1
IF (h5b == h6b) THEN
nsubh(isubh) = nsubh(isubh) + 1
ELSE
isubh = isubh + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,2.0d0/FACTORIAL(nsubh(1))/FACTORIAL(nsubh(2)),a_sort,dim_common,b_sort,dim_common&
&,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_4(c_sort,c,range(h2b),range(h1b),range(p4b),range(p3b),4,3,2,1,1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE lccsd_t2_7(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p3 p4 h1 h2 )_vt + = -1 * P( 4 ) * Sum ( h6 p5 ) * t ( p3 p5 h1 h6 )_t * v ( h6 p4 h2 p5 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: dimc
INTEGER :: p5b
INTEGER :: h6b
INTEGER :: p3b_1
INTEGER :: p5b_1
INTEGER :: h1b_1
INTEGER :: h6b_1
INTEGER :: p4b_2
INTEGER :: h6b_2
INTEGER :: h2b_2
INTEGER :: p5b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p3b = noab+1,noab+nvab
DO p4b = noab+1,noab+nvab
DO h1b = 1,noab
DO h2b = 1,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p3b)+spin(p4b)+spin(h1b)+spin(h2b) /= 8)) THEN
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h2b)))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p3b) * range(p4b) * range(h1b) * range(h2b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p5b = noab+1,noab+nvab
DO h6b = 1,noab
IF (spin(p3b)+spin(p5b) == spin(h1b)+spin(h6b)) THEN
IF (ieor(sym(p3b),ieor(sym(p5b),ieor(sym(h1b),sym(h6b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p3b,p5b,h1b,h6b,p3b_1,p5b_1,h1b_1,h6b_1)
CALL TCE_RESTRICTED_4(p4b,h6b,h2b,p5b,p4b_2,h6b_2,h2b_2,p5b_2)
dim_common = range(p5b) * range(h6b)
dima_sort = range(p3b) * range(h1b)
dima = dim_common * dima_sort
dimb_sort = range(p4b) * range(h2b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
IF ((p5b < p3b) .and. (h6b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h6b_1 - 1 + noab * (p3b_1 - noab - 1 + nvab * (p5b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p5b),range(p3b),range(h6b),range(h1b),4,2,3,1,1.0d0)
END IF
IF ((p5b < p3b) .and. (h1b <= h6b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h1b_1 - 1 + noab * (p3b_1 - noab - 1 + nvab * (p5b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p5b),range(p3b),range(h1b),range(h6b),3,2,4,1,-1.0d0)
END IF
IF ((p3b <= p5b) .and. (h6b < h1b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h1b_1 - 1 + noab * (h6b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p5b),range(h6b),range(h1b),4,1,3,2,-1.0d0)
END IF
IF ((p3b <= p5b) .and. (h1b <= h6b)) THEN
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h6b_1 - 1 + noab * (h1b_1 - 1 + noab * (p5b_1 - noab - 1 + nvab * (p3b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p3b),range(p5b),range(h1b),range(h6b),3,1,4,2,1.0d0)
END IF
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
IF ((h6b <= p4b) .and. (h2b <= p5b)) THEN
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p5b_2 - 1 + (noab+nvab) * (h2b_2 - 1 + (noab+nvab) * (p4b_2 - 1 + (noab+nvab) * (h6b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(h6b),range(p4b),range(h2b),range(p5b),3,2,1,4,1.0d0)
END IF
DEALLOCATE(b)
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,1.0d0,a_sort,dim_common,b_sort,dim_common,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
IF ((p3b <= p4b) .and. (h1b <= h2b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(p4b),range(h1b),range(p3b),4,2,3,1,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
END IF
IF ((p3b <= p4b) .and. (h2b <= h1b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(p4b),range(h1b),range(p3b),4,2,1,3,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h2b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
END IF
IF ((p4b <= p3b) .and. (h1b <= h2b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(p4b),range(h1b),range(p3b),2,4,3,1,1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p3b - noab - 1 + nvab * (p4b - noab - 1)))))
END IF
IF ((p4b <= p3b) .and. (h2b <= h1b)) THEN
CALL TCE_SORT_4(c_sort,c,range(h2b),range(p4b),range(h1b),range(p3b),2,4,1,3,-1.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h1b - 1 + noab * (h2b - 1 + noab * (p3b - noab - 1 + nvab * (p4b - noab - 1)))))
END IF
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
SUBROUTINE lccsd_t2_8(d_a,a_offset,d_b,b_offset,d_c,c_offset)
!i0 ( p3 p4 h1 h2 )_vt + = 1/2 * Sum ( p5 p6 ) * t ( p5 p6 h1 h2 )_t * v ( p3 p4 p5 p6 )_v
USE UT_SYS_MODULE
USE UT_MOLINP_MODULE
USE UT_TCE_MODULE
IMPLICIT NONE
#include "global.fh"
#include "mafdecls.fh"
INTEGER :: d_a
INTEGER :: d_b
INTEGER :: d_c
INTEGER :: next
INTEGER :: nprocs
INTEGER :: count
INTEGER :: p3b
INTEGER :: p4b
INTEGER :: h1b
INTEGER :: h2b
INTEGER :: dimc
INTEGER :: p5b
INTEGER :: p6b
INTEGER :: p5b_1
INTEGER :: p6b_1
INTEGER :: h1b_1
INTEGER :: h2b_1
INTEGER :: p3b_2
INTEGER :: p4b_2
INTEGER :: p5b_2
INTEGER :: p6b_2
INTEGER :: dim_common
INTEGER :: dima_sort
INTEGER :: dima
INTEGER :: dimb_sort
INTEGER :: dimb
INTEGER :: nsuperp(2)
INTEGER :: isuperp
INTEGER :: a_offset(*)
INTEGER :: b_offset(*)
INTEGER :: c_offset(*)
REAL*8, ALLOCATABLE :: c_sort(:)
REAL*8, ALLOCATABLE :: a_sort(:)
REAL*8, ALLOCATABLE :: a(:)
REAL*8, ALLOCATABLE :: b_sort(:)
REAL*8, ALLOCATABLE :: b(:)
REAL*8, ALLOCATABLE :: c(:)
INTEGER, EXTERNAL :: NXTVAL
REAL*8, EXTERNAL :: FACTORIAL
nprocs = GA_NNODES()
count = 0
next = NXTVAL(nprocs)
DO p3b = noab+1,noab+nvab
DO p4b = p3b,noab+nvab
DO h1b = 1,noab
DO h2b = h1b,noab
IF (next == count) THEN
IF ((.not.restricted).or.(spin(p3b)+spin(p4b)+spin(h1b)+spin(h2b) /= 8)) THEN
IF (spin(p3b)+spin(p4b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p3b),ieor(sym(p4b),ieor(sym(h1b),sym(h2b)))) == ieor(irrep_v,irrep_t)) THEN
dimc = range(p3b) * range(p4b) * range(h1b) * range(h2b)
ALLOCATE(c_sort(dimc))
c_sort = 0.0d0
DO p5b = noab+1,noab+nvab
DO p6b = p5b,noab+nvab
IF (spin(p5b)+spin(p6b) == spin(h1b)+spin(h2b)) THEN
IF (ieor(sym(p5b),ieor(sym(p6b),ieor(sym(h1b),sym(h2b)))) == irrep_t) THEN
CALL TCE_RESTRICTED_4(p5b,p6b,h1b,h2b,p5b_1,p6b_1,h1b_1,h2b_1)
CALL TCE_RESTRICTED_4(p3b,p4b,p5b,p6b,p3b_2,p4b_2,p5b_2,p6b_2)
dim_common = range(p5b) * range(p6b)
dima_sort = range(h1b) * range(h2b)
dima = dim_common * dima_sort
dimb_sort = range(p3b) * range(p4b)
dimb = dim_common * dimb_sort
IF ((dima > 0) .and. (dimb > 0)) THEN
ALLOCATE(a_sort(dima))
ALLOCATE(a(dima))
CALL GET_HASH_BLOCK(d_a,a,dima,a_offset,(h2b_1 - 1 + noab * (h1b_1 - 1 + noab * (p6b_1 - noab - 1 + nvab * (p5b_1 - noab - 1)))))
CALL TCE_SORT_4(a,a_sort,range(p5b),range(p6b),range(h1b),range(h2b),4,3,2,1,1.0d0)
DEALLOCATE(a)
ALLOCATE(b_sort(dimb))
ALLOCATE(b(dimb))
CALL GET_HASH_BLOCK(d_b,b,dimb,b_offset,(p6b_2 - 1 + (noab+nvab) * (p5b_2 - 1 + (noab+nvab) * (p4b_2 - 1 + (noab+nvab) * (p3b_2 - 1&
&)))))
CALL TCE_SORT_4(b,b_sort,range(p3b),range(p4b),range(p5b),range(p6b),2,1,4,3,1.0d0)
DEALLOCATE(b)
nsuperp(1) = 1
nsuperp(2) = 1
isuperp = 1
IF (p5b == p6b) THEN
nsuperp(isuperp) = nsuperp(isuperp) + 1
ELSE
isuperp = isuperp + 1
END IF
CALL DGEMM('T','N',dima_sort,dimb_sort,dim_common,2.0d0/FACTORIAL(nsuperp(1))/FACTORIAL(nsuperp(2)),a_sort,dim_common,b_sort,dim_co&
&mmon,1.0d0,c_sort,dima_sort)
DEALLOCATE(b_sort)
DEALLOCATE(a_sort)
END IF
END IF
END IF
END DO
END DO
ALLOCATE(c(dimc))
CALL TCE_SORT_4(c_sort,c,range(p4b),range(p3b),range(h2b),range(h1b),2,1,4,3,1.0d0/2.0d0)
CALL ADD_HASH_BLOCK(d_c,c,dimc,c_offset,(h2b - 1 + noab * (h1b - 1 + noab * (p4b - noab - 1 + nvab * (p3b - noab - 1)))))
DEALLOCATE(c)
DEALLOCATE(c_sort)
END IF
END IF
END IF
next = NXTVAL(nprocs)
END IF
count = count + 1
END DO
END DO
END DO
END DO
next = NXTVAL(-nprocs)
call GA_SYNC()
RETURN
END
